# -*- coding: utf-8 -*-
# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #

from __future__ import annotations

from typing import List, Union

from pydantic import Field

from ..abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class LocationQueryResponse(EventTypeAbstractModel):
    Meta_: LocationQueryResponseMeta = Field(..., alias="Meta")
    Patients_: List[LocationQueryResponsePatient] = Field(..., alias="Patients")


class LocationQueryResponseMeta(RedoxAbstractModel):
    DataModel_: str = Field(..., alias="DataModel")
    Destinations_: List[LocationQueryResponseMetaDestination] = Field(
        None, alias="Destinations"
    )
    EventDateTime_: Union[str, None] = Field(None, alias="EventDateTime")
    EventType_: str = Field(..., alias="EventType")
    FacilityCode_: Union[str, None] = Field(None, alias="FacilityCode")
    Logs_: List[LocationQueryResponseMetaLog] = Field(None, alias="Logs")
    Message_: LocationQueryResponseMetaMessage = Field(None, alias="Message")
    Source_: LocationQueryResponseMetaSource = Field(None, alias="Source")
    Test_: Union[bool, None] = Field(None, alias="Test")
    Transmission_: LocationQueryResponseMetaTransmission = Field(
        None, alias="Transmission"
    )


class LocationQueryResponseMetaDestination(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    Name_: Union[str, None] = Field(None, alias="Name")


class LocationQueryResponseMetaLog(RedoxAbstractModel):
    AttemptID_: Union[str, None] = Field(None, alias="AttemptID")
    ID_: Union[str, None] = Field(None, alias="ID")


class LocationQueryResponseMetaMessage(RedoxAbstractModel):
    ID_: Union[float, None] = Field(None, alias="ID")


class LocationQueryResponseMetaSource(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    Name_: Union[str, None] = Field(None, alias="Name")


class LocationQueryResponseMetaTransmission(RedoxAbstractModel):
    ID_: Union[float, None] = Field(None, alias="ID")


class LocationQueryResponsePatient(RedoxAbstractModel):
    Identifiers_: List[LocationQueryResponsePatientIdentifier] = Field(
        ..., alias="Identifiers"
    )
    Organization_: LocationQueryResponsePatientOrganization = Field(
        None, alias="Organization"
    )


class LocationQueryResponsePatientIdentifier(RedoxAbstractModel):
    ID_: str = Field(..., alias="ID")
    IDType_: str = Field(..., alias="IDType")


class LocationQueryResponsePatientOrganization(RedoxAbstractModel):
    Address_: LocationQueryResponsePatientOrganizationAddress = Field(
        None, alias="Address"
    )
    Aliases_: List[str] = Field(None, alias="Aliases")
    Contacts_: List[LocationQueryResponsePatientOrganizationContact] = Field(
        None, alias="Contacts"
    )
    Identifiers_: List[LocationQueryResponsePatientOrganizationIdentifier] = Field(
        None, alias="Identifiers"
    )
    Name_: Union[str, None] = Field(None, alias="Name")


class LocationQueryResponsePatientOrganizationAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class LocationQueryResponsePatientOrganizationContact(RedoxAbstractModel):
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    Name_: Union[str, None] = Field(None, alias="Name")
    PhoneNumber_: LocationQueryResponsePatientOrganizationContactPhoneNumber = Field(
        None, alias="PhoneNumber"
    )
    Purpose_: Union[str, None] = Field(None, alias="Purpose")


class LocationQueryResponsePatientOrganizationContactPhoneNumber(RedoxAbstractModel):
    Home_: Union[str, None] = Field(None, alias="Home")
    Mobile_: Union[str, None] = Field(None, alias="Mobile")
    Work_: Union[str, None] = Field(None, alias="Work")


class LocationQueryResponsePatientOrganizationIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


LocationQueryResponse.model_rebuild()
LocationQueryResponseMeta.model_rebuild()
LocationQueryResponsePatient.model_rebuild()
LocationQueryResponsePatientOrganization.model_rebuild()
LocationQueryResponsePatientOrganizationContact.model_rebuild()
