# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #
from __future__ import annotations

from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class Response(EventTypeAbstractModel):
    Meta: ResponseMeta = Field(..., alias="Meta")
    Patient: ResponsePatient = Field(None, alias="Patient")
    PotentialMatches: list[ResponsePotentialMatch] = Field(None, alias="PotentialMatches")


class ResponseMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list[ResponseMetaDestination] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    IsIncomplete: bool | None = Field(None, alias="IsIncomplete")
    Logs: list[ResponseMetaLog] = Field(None, alias="Logs")
    Source: ResponseMetaSource = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class ResponseMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class ResponseMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class ResponseMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class ResponsePatient(RedoxAbstractModel):
    Contacts: list[ResponsePatientContact] = Field(None, alias="Contacts")
    Demographics: ResponsePatientDemographics = Field(None, alias="Demographics")
    Guarantor: ResponsePatientGuarantor = Field(None, alias="Guarantor")
    Identifiers: list[ResponsePatientIdentifier] = Field(None, alias="Identifiers")
    Insurances: list[ResponsePatientInsurance] = Field(None, alias="Insurances")
    Notes: list[str] = Field(None, alias="Notes")
    PCP: ResponsePatientPCP = Field(None, alias="PCP")


class ResponsePatientContact(RedoxAbstractModel):
    Address: ResponsePatientContactAddress = Field(None, alias="Address")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: ResponsePatientContactPhoneNumber = Field(None, alias="PhoneNumber")
    RelationToPatient: str | None = Field(None, alias="RelationToPatient")
    Roles: list[str] = Field(None, alias="Roles")


class ResponsePatientContactAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePatientContactPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class ResponsePatientDemographics(RedoxAbstractModel):
    Address: ResponsePatientDemographicsAddress = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: ResponsePatientDemographicsPhoneNumber = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class ResponsePatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class ResponsePatientGuarantor(RedoxAbstractModel):
    Address: ResponsePatientGuarantorAddress = Field(None, alias="Address")
    DOB: str | None = Field(None, alias="DOB")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    Employer: ResponsePatientGuarantorEmployer = Field(None, alias="Employer")
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    Number: str | None = Field(None, alias="Number")
    PhoneNumber: ResponsePatientGuarantorPhoneNumber = Field(None, alias="PhoneNumber")
    RelationToPatient: str | None = Field(None, alias="RelationToPatient")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")
    Spouse: ResponsePatientGuarantorSpouse = Field(None, alias="Spouse")
    Type: str | None = Field(None, alias="Type")


class ResponsePatientGuarantorAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePatientGuarantorEmployer(RedoxAbstractModel):
    Address: ResponsePatientGuarantorEmployerAddress = Field(None, alias="Address")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class ResponsePatientGuarantorEmployerAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePatientGuarantorPhoneNumber(RedoxAbstractModel):
    Business: str | None = Field(None, alias="Business")
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")


class ResponsePatientGuarantorSpouse(RedoxAbstractModel):
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")


class ResponsePatientIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ResponsePatientInsurance(RedoxAbstractModel):
    AgreementType: str | None = Field(None, alias="AgreementType")
    Company: ResponsePatientInsuranceCompany = Field(None, alias="Company")
    CoverageType: str | None = Field(None, alias="CoverageType")
    EffectiveDate: str | None = Field(None, alias="EffectiveDate")
    ExpirationDate: str | None = Field(None, alias="ExpirationDate")
    GroupName: str | None = Field(None, alias="GroupName")
    GroupNumber: str | None = Field(None, alias="GroupNumber")
    Insured: ResponsePatientInsuranceInsured = Field(None, alias="Insured")
    MemberNumber: str | None = Field(None, alias="MemberNumber")
    Plan: ResponsePatientInsurancePlan = Field(None, alias="Plan")
    PolicyNumber: str | None = Field(None, alias="PolicyNumber")
    Priority: str | None = Field(None, alias="Priority")


class ResponsePatientInsuranceCompany(RedoxAbstractModel):
    Address: ResponsePatientInsuranceCompanyAddress = Field(None, alias="Address")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class ResponsePatientInsuranceCompanyAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePatientInsuranceInsured(RedoxAbstractModel):
    Address: ResponsePatientInsuranceInsuredAddress = Field(None, alias="Address")
    DOB: str | None = Field(None, alias="DOB")
    FirstName: str | None = Field(None, alias="FirstName")
    Identifiers: list[ResponsePatientInsuranceInsuredIdentifier] = Field(None, alias="Identifiers")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    Relationship: str | None = Field(None, alias="Relationship")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class ResponsePatientInsuranceInsuredAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePatientInsuranceInsuredIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ResponsePatientInsurancePlan(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class ResponsePatientPCP(RedoxAbstractModel):
    Address: ResponsePatientPCPAddress = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: ResponsePatientPCPLocation = Field(None, alias="Location")
    NPI: str | None = Field(None, alias="NPI")
    PhoneNumber: ResponsePatientPCPPhoneNumber = Field(None, alias="PhoneNumber")


class ResponsePatientPCPAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePatientPCPLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list[ResponsePatientPCPLocationDepartmentIdentifier] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list[ResponsePatientPCPLocationFacilityIdentifier] = Field(None, alias="FacilityIdentifiers")
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class ResponsePatientPCPLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ResponsePatientPCPLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ResponsePatientPCPPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class ResponsePotentialMatch(RedoxAbstractModel):
    Contacts: list[ResponsePotentialMatchContact] = Field(None, alias="Contacts")
    Demographics: ResponsePotentialMatchDemographics = Field(None, alias="Demographics")
    Guarantor: ResponsePotentialMatchGuarantor = Field(None, alias="Guarantor")
    Identifiers: list[ResponsePotentialMatchIdentifier] = Field(None, alias="Identifiers")
    Insurances: list[ResponsePotentialMatchInsurance] = Field(None, alias="Insurances")
    Notes: list[str] = Field(None, alias="Notes")
    PCP: ResponsePotentialMatchPCP = Field(None, alias="PCP")


class ResponsePotentialMatchContact(RedoxAbstractModel):
    Address: ResponsePotentialMatchContactAddress = Field(None, alias="Address")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: ResponsePotentialMatchContactPhoneNumber = Field(None, alias="PhoneNumber")
    RelationToPatient: str | None = Field(None, alias="RelationToPatient")
    Roles: list[str] = Field(None, alias="Roles")


class ResponsePotentialMatchContactAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePotentialMatchContactPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class ResponsePotentialMatchDemographics(RedoxAbstractModel):
    Address: ResponsePotentialMatchDemographicsAddress = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: ResponsePotentialMatchDemographicsPhoneNumber = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class ResponsePotentialMatchDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePotentialMatchDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class ResponsePotentialMatchGuarantor(RedoxAbstractModel):
    Address: ResponsePotentialMatchGuarantorAddress = Field(None, alias="Address")
    DOB: str | None = Field(None, alias="DOB")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    Employer: ResponsePotentialMatchGuarantorEmployer = Field(None, alias="Employer")
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    Number: str | None = Field(None, alias="Number")
    PhoneNumber: ResponsePotentialMatchGuarantorPhoneNumber = Field(None, alias="PhoneNumber")
    RelationToPatient: str | None = Field(None, alias="RelationToPatient")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")
    Spouse: ResponsePotentialMatchGuarantorSpouse = Field(None, alias="Spouse")
    Type: str | None = Field(None, alias="Type")


class ResponsePotentialMatchGuarantorAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePotentialMatchGuarantorEmployer(RedoxAbstractModel):
    Address: ResponsePotentialMatchGuarantorEmployerAddress = Field(None, alias="Address")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class ResponsePotentialMatchGuarantorEmployerAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePotentialMatchGuarantorPhoneNumber(RedoxAbstractModel):
    Business: str | None = Field(None, alias="Business")
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")


class ResponsePotentialMatchGuarantorSpouse(RedoxAbstractModel):
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")


class ResponsePotentialMatchIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ResponsePotentialMatchInsurance(RedoxAbstractModel):
    AgreementType: str | None = Field(None, alias="AgreementType")
    Company: ResponsePotentialMatchInsuranceCompany = Field(None, alias="Company")
    CoverageType: str | None = Field(None, alias="CoverageType")
    EffectiveDate: str | None = Field(None, alias="EffectiveDate")
    ExpirationDate: str | None = Field(None, alias="ExpirationDate")
    GroupName: str | None = Field(None, alias="GroupName")
    GroupNumber: str | None = Field(None, alias="GroupNumber")
    Insured: ResponsePotentialMatchInsuranceInsured = Field(None, alias="Insured")
    MemberNumber: str | None = Field(None, alias="MemberNumber")
    Plan: ResponsePotentialMatchInsurancePlan = Field(None, alias="Plan")
    PolicyNumber: str | None = Field(None, alias="PolicyNumber")
    Priority: str | None = Field(None, alias="Priority")


class ResponsePotentialMatchInsuranceCompany(RedoxAbstractModel):
    Address: ResponsePotentialMatchInsuranceCompanyAddress = Field(None, alias="Address")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class ResponsePotentialMatchInsuranceCompanyAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePotentialMatchInsuranceInsured(RedoxAbstractModel):
    Address: ResponsePotentialMatchInsuranceInsuredAddress = Field(None, alias="Address")
    DOB: str | None = Field(None, alias="DOB")
    FirstName: str | None = Field(None, alias="FirstName")
    Identifiers: list[ResponsePotentialMatchInsuranceInsuredIdentifier] = Field(None, alias="Identifiers")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    Relationship: str | None = Field(None, alias="Relationship")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class ResponsePotentialMatchInsuranceInsuredAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePotentialMatchInsuranceInsuredIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ResponsePotentialMatchInsurancePlan(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class ResponsePotentialMatchPCP(RedoxAbstractModel):
    Address: ResponsePotentialMatchPCPAddress = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: ResponsePotentialMatchPCPLocation = Field(None, alias="Location")
    NPI: str | None = Field(None, alias="NPI")
    PhoneNumber: ResponsePotentialMatchPCPPhoneNumber = Field(None, alias="PhoneNumber")


class ResponsePotentialMatchPCPAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ResponsePotentialMatchPCPLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list[ResponsePotentialMatchPCPLocationDepartmentIdentifier] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list[ResponsePotentialMatchPCPLocationFacilityIdentifier] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class ResponsePotentialMatchPCPLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ResponsePotentialMatchPCPLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ResponsePotentialMatchPCPPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


Response.model_rebuild()
ResponseMeta.model_rebuild()
ResponsePatient.model_rebuild()
ResponsePatientContact.model_rebuild()
ResponsePatientDemographics.model_rebuild()
ResponsePatientGuarantor.model_rebuild()
ResponsePatientGuarantorEmployer.model_rebuild()
ResponsePatientInsurance.model_rebuild()
ResponsePatientInsuranceCompany.model_rebuild()
ResponsePatientInsuranceInsured.model_rebuild()
ResponsePatientPCP.model_rebuild()
ResponsePatientPCPLocation.model_rebuild()
ResponsePotentialMatch.model_rebuild()
ResponsePotentialMatchContact.model_rebuild()
ResponsePotentialMatchDemographics.model_rebuild()
ResponsePotentialMatchGuarantor.model_rebuild()
ResponsePotentialMatchGuarantorEmployer.model_rebuild()
ResponsePotentialMatchInsurance.model_rebuild()
ResponsePotentialMatchInsuranceCompany.model_rebuild()
ResponsePotentialMatchInsuranceInsured.model_rebuild()
ResponsePotentialMatchPCP.model_rebuild()
ResponsePotentialMatchPCPLocation.model_rebuild()
