# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class New(EventTypeAbstractModel):
    Education: list["NewEducation"] = Field(..., alias="Education")
    Meta: "NewMeta" = Field(..., alias="Meta")
    Patient: "NewPatient" = Field(..., alias="Patient")
    Visit: "NewVisit" = Field(None, alias="Visit")


class NewEducation(RedoxAbstractModel):
    ActionDateTime: str | None = Field(None, alias="ActionDateTime")
    ActionStatus: str | None = Field(None, alias="ActionStatus")
    Assignments: list["NewEducationAssignment"] = Field(None, alias="Assignments")
    CreatedDateTime: str | None = Field(None, alias="CreatedDateTime")
    InstanceID: str | None = Field(None, alias="InstanceID")
    Status: str | None = Field(None, alias="Status")
    Subject: "NewEducationSubject" = Field(..., alias="Subject")


class NewEducationAssignment(RedoxAbstractModel):
    ActionDateTime: str | None = Field(None, alias="ActionDateTime")
    ActionStatus: str | None = Field(None, alias="ActionStatus")
    Assignees: list["NewEducationAssignmentAssignee"] = Field(None, alias="Assignees")
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    CreatedDateTime: str | None = Field(None, alias="CreatedDateTime")
    Description: str | None = Field(None, alias="Description")
    InstanceID: str | None = Field(None, alias="InstanceID")
    Status: str | None = Field(None, alias="Status")
    Topic: "NewEducationAssignmentTopic" = Field(None, alias="Topic")


class NewEducationAssignmentAssignee(RedoxAbstractModel):
    ContentType: str | None = Field(None, alias="ContentType")
    Learner: str | None = Field(None, alias="Learner")
    Notes: list[str] = Field(None, alias="Notes")
    Readiness: str | None = Field(None, alias="Readiness")
    Response: str | None = Field(None, alias="Response")


class NewEducationAssignmentTopic(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


class NewEducationSubject(RedoxAbstractModel):
    Code: str = Field(..., alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


class NewMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["NewMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["NewMetaLog"] = Field(None, alias="Logs")
    Source: "NewMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class NewMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class NewMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class NewMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class NewPatient(RedoxAbstractModel):
    Demographics: "NewPatientDemographics" = Field(None, alias="Demographics")
    Identifiers: list["NewPatientIdentifier"] = Field(..., alias="Identifiers")
    Notes: list[str] = Field(None, alias="Notes")


class NewPatientDemographics(RedoxAbstractModel):
    Address: "NewPatientDemographicsAddress" = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "NewPatientDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class NewPatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewPatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class NewPatientIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str = Field(..., alias="IDType")


class NewVisit(RedoxAbstractModel):
    AccountNumber: str | None = Field(None, alias="AccountNumber")
    AttendingProvider: "NewVisitAttendingProvider" = Field(None, alias="AttendingProvider")
    ConsultingProvider: "NewVisitConsultingProvider" = Field(None, alias="ConsultingProvider")
    Location: "NewVisitLocation" = Field(None, alias="Location")
    PatientClass: str | None = Field(None, alias="PatientClass")
    ReferringProvider: "NewVisitReferringProvider" = Field(None, alias="ReferringProvider")
    VisitDateTime: str | None = Field(None, alias="VisitDateTime")
    VisitNumber: str | None = Field(None, alias="VisitNumber")


class NewVisitAttendingProvider(RedoxAbstractModel):
    Address: "NewVisitAttendingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "NewVisitAttendingProviderLocation" = Field(None, alias="Location")
    NPI: str | None = Field(None, alias="NPI")
    PhoneNumber: "NewVisitAttendingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class NewVisitAttendingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewVisitAttendingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NewVisitAttendingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NewVisitAttendingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NewVisitAttendingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewVisitAttendingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewVisitAttendingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class NewVisitConsultingProvider(RedoxAbstractModel):
    Address: "NewVisitConsultingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "NewVisitConsultingProviderLocation" = Field(None, alias="Location")
    NPI: str | None = Field(None, alias="NPI")
    PhoneNumber: "NewVisitConsultingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class NewVisitConsultingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewVisitConsultingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NewVisitConsultingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NewVisitConsultingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NewVisitConsultingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewVisitConsultingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewVisitConsultingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class NewVisitLocation(RedoxAbstractModel):
    Bed: str | None = Field(None, alias="Bed")
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NewVisitLocationDepartmentIdentifier"] = Field(None, alias="DepartmentIdentifiers")
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NewVisitLocationFacilityIdentifier"] = Field(None, alias="FacilityIdentifiers")
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NewVisitLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewVisitLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewVisitReferringProvider(RedoxAbstractModel):
    Address: "NewVisitReferringProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "NewVisitReferringProviderLocation" = Field(None, alias="Location")
    NPI: str | None = Field(None, alias="NPI")
    PhoneNumber: "NewVisitReferringProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class NewVisitReferringProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewVisitReferringProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NewVisitReferringProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NewVisitReferringProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NewVisitReferringProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewVisitReferringProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewVisitReferringProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


New.model_rebuild()
NewEducation.model_rebuild()
NewEducationAssignment.model_rebuild()
NewMeta.model_rebuild()
NewPatient.model_rebuild()
NewPatientDemographics.model_rebuild()
NewVisit.model_rebuild()
NewVisitAttendingProvider.model_rebuild()
NewVisitAttendingProviderLocation.model_rebuild()
NewVisitConsultingProvider.model_rebuild()
NewVisitConsultingProviderLocation.model_rebuild()
NewVisitLocation.model_rebuild()
NewVisitReferringProvider.model_rebuild()
NewVisitReferringProviderLocation.model_rebuild()
