# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #
"""Round-trip every Redox sample payload through its model and back."""

from json import loads
from pathlib import Path

import pytest

import redox
from redox.factory import get_class_type, redox_object_factory

FIXTURES_DIR = (Path(__file__).parent / "fixtures").resolve()
REDOX_PKG_DIR = Path(redox.__file__).parent

# Only exercise fixtures whose event module still exists in the current schema
# (Redox retires data models over time, e.g. claim/submission).
_GENERATED_EVENTS = {
    f"{module.name}_{event.stem}.json"
    for module in REDOX_PKG_DIR.iterdir()
    if module.is_dir() and module.name != "generic" and not module.name.startswith("_")
    for event in module.glob("*.py")
    if not event.name.startswith("_")
}
FIXTURES = sorted(p for p in FIXTURES_DIR.glob("*.json") if p.name in _GENERATED_EVENTS)


@pytest.mark.parametrize("fixture", FIXTURES, ids=lambda p: p.name)
def test_direct_construction_round_trips(fixture: Path):
    sample = loads(fixture.read_text())
    model = get_class_type(sample)
    obj = model(**sample)
    assert isinstance(obj, model)
    assert obj.model_dump() == sample


@pytest.mark.parametrize("fixture", FIXTURES, ids=lambda p: p.name)
def test_factory_round_trips(fixture: Path):
    sample = loads(fixture.read_text())
    obj = redox_object_factory(sample)
    assert isinstance(obj, get_class_type(sample))
    assert obj.model_dump() == sample
