# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #
"""Base classes shared by every Redox model.

This file is vendored from ``gen_redox_lib`` and copied into the ``redox``
package on every regeneration - edit it there, not here.
"""

import warnings
from collections.abc import Iterator, Mapping
from contextlib import contextmanager
from contextvars import ContextVar
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, ValidationError, model_validator

__all__ = [
    "CannotRectifyValidationError",
    "EventTypeAbstractModel",
    "GenericEventTypeAbstractModel",
    "MetaBase",
    "RedoxAbstractModel",
    "lenient_ingest",
]

# When set, model validation recursively drops keys that aren't part of the
# target model instead of raising ``extra_forbidden``. Opt in with
# ``lenient_ingest()`` or ``redox_object_factory(..., lenient=True)``.
_LENIENT: ContextVar[bool] = ContextVar("_LENIENT", default=False)


@contextmanager
def lenient_ingest() -> Iterator[None]:
    """Parse Redox payloads tolerantly within this block.

    Unknown fields (e.g. a schema addition Redox shipped before the library was
    regenerated) are silently dropped rather than raising. Serialization and
    outbound validation are unaffected - this only relaxes parsing.
    """
    token = _LENIENT.set(True)
    try:
        yield
    finally:
        _LENIENT.reset(token)


class CannotRectifyValidationError(Exception):
    """Raised when ``cast_from`` can't autocorrect a ``ValidationError``."""


def _pop_offending_field_values(args_for_new_object: dict, validation_err: ValidationError) -> None:
    for err in validation_err.errors():
        if err["type"] != "extra_forbidden":
            msg = f"Unknown validation error type: {err['type']}"
            raise CannotRectifyValidationError(msg)

        parent = args_for_new_object
        locations = list(err["loc"])
        offending_field = locations.pop()
        traversed: list[str] = []
        for field in locations:
            next_in_loc = parent.get(field) if isinstance(parent, dict) else None
            if not next_in_loc:
                joined = "->".join(traversed) if traversed else "Object"
                msg = f'Cannot traverse to offending field: {joined} has no field "{field}".'
                raise CannotRectifyValidationError(msg)
            traversed.append(str(field))
            parent = next_in_loc

        try:
            parent.pop(offending_field)
        except (KeyError, AttributeError) as err:
            joined = "->".join(traversed) if traversed else "Object"
            msg = f'Cannot traverse to offending field: {joined} has no field "{offending_field}".'
            raise CannotRectifyValidationError(msg) from err


class RedoxAbstractModel(BaseModel):
    """Common configuration and helpers for every Redox model."""

    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        coerce_numbers_to_str=True,
    )

    Extensions: Any = Field(None, alias="Extensions")

    @model_validator(mode="before")
    @classmethod
    def _drop_unknown_when_lenient(cls, data: Any) -> Any:
        if _LENIENT.get() and isinstance(data, dict):
            allowed: set[str] = set()
            for name, field in cls.model_fields.items():
                allowed.add(name)
                if field.alias:
                    allowed.add(field.alias)
            return {k: v for k, v in data.items() if k in allowed}
        return data

    @classmethod
    def cast_from(cls, *others: "RedoxAbstractModel | Mapping") -> "RedoxAbstractModel":
        """Build a new Redox object from the fields of ``others``.

        Intended for assigning the same values to several models while avoiding
        type-checking errors - e.g. reusing one provider across the several
        provider roles on a ``Visit``::

            provider = AdmittingProvider(...)
            visit = Visit(
                AdmittingProvider=provider,
                AttendingProvider=AttendingProvider.cast_from(provider),
                VisitProvider=VisitProvider.cast_from(provider),
            )

        Earlier arguments win over later ones (mirroring MRO).
        """
        dumped = [
            other.model_dump() if isinstance(other, RedoxAbstractModel) else dict(other) for other in reversed(others)
        ]
        args: dict[str, Any] = {}
        for other in dumped:
            args.update(other)

        new_object = None
        while new_object is None:
            try:
                new_object = cls(**args)
            except ValidationError as err:
                _pop_offending_field_values(args, err)
        return new_object

    # Redox-shaped defaults: emit aliases, drop unset/null fields. Callers can
    # still override any of these. Kept as **kwargs so the signature stays
    # compatible as pydantic evolves BaseModel.model_dump*.
    _REDOX_DUMP_DEFAULTS = {"by_alias": True, "exclude_unset": True, "exclude_none": True}

    def model_dump(self, **kwargs: Any) -> dict[str, Any]:
        """Dump to a dict, defaulting to Redox-shaped output (aliases, no nulls)."""
        for key, value in self._REDOX_DUMP_DEFAULTS.items():
            kwargs.setdefault(key, value)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs: Any) -> str:
        """Dump to a JSON string, with the same Redox-shaped defaults as ``model_dump``."""
        for key, value in self._REDOX_DUMP_DEFAULTS.items():
            kwargs.setdefault(key, value)
        return super().model_dump_json(**kwargs)

    def dict(self, **kwargs: Any) -> dict[str, Any]:
        """Deprecated Pydantic v1 alias for :meth:`model_dump`."""
        warnings.warn(
            "`.dict()` is deprecated; use `.model_dump()` instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return self.model_dump(**kwargs)

    def json(self, **kwargs: Any) -> str:
        """Deprecated Pydantic v1 alias for :meth:`model_dump_json`."""
        warnings.warn(
            "`.json()` is deprecated; use `.model_dump_json()` instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return self.model_dump_json(**kwargs)


class MetaBase(RedoxAbstractModel):
    """The fields common to every ``Meta`` object."""

    DataModel: str = Field(..., alias="DataModel")
    EventType: str = Field(..., alias="EventType")


class EventTypeAbstractModel(RedoxAbstractModel):
    """Base class for the "proper Redox" event-type models."""

    Meta: MetaBase = Field(..., alias="Meta")


class GenericEventTypeAbstractModel(RedoxAbstractModel):
    """Base class for the composable ``redox.generic`` event-type models."""

    _redox_module: Any = None  # set by each subclass, e.g. `patientadmin`
    Meta: MetaBase = Field(..., alias="Meta")

    def to_redox(self) -> RedoxAbstractModel:
        """Resolve and instantiate the matching "proper Redox" model."""
        class_name = type(self).__name__
        event_module = getattr(self._redox_module, class_name.lower(), None)
        if event_module is None:
            msg = f"Couldn't find Redox event module for {class_name.lower()}"
            raise AttributeError(msg)
        event_class = getattr(event_module, class_name, None)
        if event_class is None:
            msg = f"Couldn't find Redox event class for {class_name}"
            raise AttributeError(msg)
        return event_class.model_validate(super().model_dump())

    def redox_dict(self, **kwargs: Any) -> dict[str, Any]:
        """Convert to the proper Redox model, then :meth:`model_dump` it."""
        return self.to_redox().model_dump(**kwargs)

    def redox_json(self, **kwargs: Any) -> str:
        """Convert to the proper Redox model, then :meth:`model_dump_json` it."""
        return self.to_redox().model_dump_json(**kwargs)

    def dict(self, **kwargs: Any) -> dict[str, Any]:
        """Deprecated alias; converts to the proper Redox model first."""
        warnings.warn(
            "`.dict()` is deprecated; use `.redox_dict()` or `.model_dump()` instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return self.redox_dict(**kwargs)

    def json(self, **kwargs: Any) -> str:
        """Deprecated alias; converts to the proper Redox model first."""
        warnings.warn(
            "`.json()` is deprecated; use `.redox_json()` or `.model_dump_json()` instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return self.redox_json(**kwargs)
