# -*- coding: utf-8 -*-
# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #

from __future__ import annotations

from typing import List, Union

from pydantic import Field

from ..abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class Update(EventTypeAbstractModel):
    Meta_: UpdateMeta = Field(..., alias="Meta")
    Order_: UpdateOrder = Field(..., alias="Order")
    Patient_: UpdatePatient = Field(..., alias="Patient")
    Visit_: UpdateVisit = Field(None, alias="Visit")


class UpdateMeta(RedoxAbstractModel):
    DataModel_: str = Field(..., alias="DataModel")
    Destinations_: List[UpdateMetaDestination] = Field(None, alias="Destinations")
    EventDateTime_: Union[str, None] = Field(None, alias="EventDateTime")
    EventType_: str = Field(..., alias="EventType")
    FacilityCode_: Union[str, None] = Field(None, alias="FacilityCode")
    Logs_: List[UpdateMetaLog] = Field(None, alias="Logs")
    Message_: UpdateMetaMessage = Field(None, alias="Message")
    Source_: UpdateMetaSource = Field(None, alias="Source")
    Test_: Union[bool, None] = Field(None, alias="Test")
    Transmission_: UpdateMetaTransmission = Field(None, alias="Transmission")


class UpdateMetaDestination(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdateMetaLog(RedoxAbstractModel):
    AttemptID_: Union[str, None] = Field(None, alias="AttemptID")
    ID_: Union[str, None] = Field(None, alias="ID")


class UpdateMetaMessage(RedoxAbstractModel):
    ID_: Union[float, None] = Field(None, alias="ID")


class UpdateMetaSource(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdateMetaTransmission(RedoxAbstractModel):
    ID_: Union[float, None] = Field(None, alias="ID")


class UpdateOrder(RedoxAbstractModel):
    EnteredBy_: UpdateOrderEnteredBy = Field(None, alias="EnteredBy")
    ID_: str = Field(..., alias="ID")
    Indications_: List[UpdateOrderIndication] = Field(None, alias="Indications")
    Medication_: UpdateOrderMedication = Field(..., alias="Medication")
    Notes_: List[str] = Field(None, alias="Notes")
    Pharmacy_: UpdateOrderPharmacy = Field(None, alias="Pharmacy")
    Priority_: Union[str, None] = Field(None, alias="Priority")
    Provider_: UpdateOrderProvider = Field(None, alias="Provider")
    VerifiedBy_: UpdateOrderVerifiedBy = Field(None, alias="VerifiedBy")


class UpdateOrderEnteredBy(RedoxAbstractModel):
    Address_: UpdateOrderEnteredByAddress = Field(None, alias="Address")
    Credentials_: List[str] = Field(None, alias="Credentials")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    Location_: UpdateOrderEnteredByLocation = Field(None, alias="Location")
    PhoneNumber_: UpdateOrderEnteredByPhoneNumber = Field(None, alias="PhoneNumber")


class UpdateOrderEnteredByAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdateOrderEnteredByLocation(RedoxAbstractModel):
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[
        UpdateOrderEnteredByLocationDepartmentIdentifier
    ] = Field(None, alias="DepartmentIdentifiers")
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[UpdateOrderEnteredByLocationFacilityIdentifier] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class UpdateOrderEnteredByLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateOrderEnteredByLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateOrderEnteredByPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


class UpdateOrderIndication(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    Codeset_: Union[str, None] = Field(None, alias="Codeset")
    Description_: Union[str, None] = Field(None, alias="Description")


class UpdateOrderMedication(RedoxAbstractModel):
    Components_: List[UpdateOrderMedicationComponent] = Field(None, alias="Components")
    Dispense_: UpdateOrderMedicationDispense = Field(None, alias="Dispense")
    Dose_: UpdateOrderMedicationDose = Field(None, alias="Dose")
    EndDate_: Union[str, None] = Field(None, alias="EndDate")
    FreeTextSig_: Union[str, None] = Field(None, alias="FreeTextSig")
    Frequency_: UpdateOrderMedicationFrequency = Field(None, alias="Frequency")
    IsPRN_: Union[bool, None] = Field(None, alias="IsPRN")
    NumberOfRefillsRemaining_: Union[float, None] = Field(
        None, alias="NumberOfRefillsRemaining"
    )
    Product_: UpdateOrderMedicationProduct = Field(..., alias="Product")
    Rate_: UpdateOrderMedicationRate = Field(None, alias="Rate")
    Route_: UpdateOrderMedicationRoute = Field(None, alias="Route")
    StartDate_: Union[str, None] = Field(None, alias="StartDate")


class UpdateOrderMedicationComponent(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Dose_: UpdateOrderMedicationComponentDose = Field(None, alias="Dose")
    Name_: Union[str, None] = Field(None, alias="Name")
    Type_: Union[str, None] = Field(None, alias="Type")


class UpdateOrderMedicationComponentDose(RedoxAbstractModel):
    Quantity_: Union[float, None] = Field(None, alias="Quantity")
    Units_: Union[str, None] = Field(None, alias="Units")


class UpdateOrderMedicationDispense(RedoxAbstractModel):
    Amount_: Union[float, None] = Field(None, alias="Amount")
    Units_: Union[str, None] = Field(None, alias="Units")


class UpdateOrderMedicationDose(RedoxAbstractModel):
    Quantity_: Union[float, None] = Field(None, alias="Quantity")
    Units_: Union[str, None] = Field(None, alias="Units")


class UpdateOrderMedicationFrequency(RedoxAbstractModel):
    Period_: Union[float, None] = Field(None, alias="Period")
    Unit_: Union[str, None] = Field(None, alias="Unit")


class UpdateOrderMedicationProduct(RedoxAbstractModel):
    AltCodes_: List[UpdateOrderMedicationProductAltCode] = Field(None, alias="AltCodes")
    Code_: str = Field(..., alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdateOrderMedicationProductAltCode(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdateOrderMedicationRate(RedoxAbstractModel):
    Quantity_: Union[float, None] = Field(None, alias="Quantity")
    Units_: Union[str, None] = Field(None, alias="Units")


class UpdateOrderMedicationRoute(RedoxAbstractModel):
    AltCodes_: List[UpdateOrderMedicationRouteAltCode] = Field(None, alias="AltCodes")
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdateOrderMedicationRouteAltCode(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdateOrderPharmacy(RedoxAbstractModel):
    Address_: UpdateOrderPharmacyAddress = Field(None, alias="Address")
    Code_: Union[str, None] = Field(None, alias="Code")
    Codeset_: Union[str, None] = Field(None, alias="Codeset")
    Description_: Union[str, None] = Field(None, alias="Description")
    PhoneNumber_: UpdateOrderPharmacyPhoneNumber = Field(None, alias="PhoneNumber")


class UpdateOrderPharmacyAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdateOrderPharmacyPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


class UpdateOrderProvider(RedoxAbstractModel):
    Address_: UpdateOrderProviderAddress = Field(None, alias="Address")
    Credentials_: List[str] = Field(None, alias="Credentials")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    Location_: UpdateOrderProviderLocation = Field(None, alias="Location")
    NPI_: Union[str, None] = Field(None, alias="NPI")
    PhoneNumber_: UpdateOrderProviderPhoneNumber = Field(None, alias="PhoneNumber")


class UpdateOrderProviderAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdateOrderProviderLocation(RedoxAbstractModel):
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[
        UpdateOrderProviderLocationDepartmentIdentifier
    ] = Field(None, alias="DepartmentIdentifiers")
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[UpdateOrderProviderLocationFacilityIdentifier] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class UpdateOrderProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateOrderProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateOrderProviderPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


class UpdateOrderVerifiedBy(RedoxAbstractModel):
    Address_: UpdateOrderVerifiedByAddress = Field(None, alias="Address")
    Credentials_: List[str] = Field(None, alias="Credentials")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    Location_: UpdateOrderVerifiedByLocation = Field(None, alias="Location")
    PhoneNumber_: UpdateOrderVerifiedByPhoneNumber = Field(None, alias="PhoneNumber")


class UpdateOrderVerifiedByAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdateOrderVerifiedByLocation(RedoxAbstractModel):
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[
        UpdateOrderVerifiedByLocationDepartmentIdentifier
    ] = Field(None, alias="DepartmentIdentifiers")
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[UpdateOrderVerifiedByLocationFacilityIdentifier] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class UpdateOrderVerifiedByLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateOrderVerifiedByLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateOrderVerifiedByPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


class UpdatePatient(RedoxAbstractModel):
    Allergies_: List[UpdatePatientAllergy] = Field(None, alias="Allergies")
    Demographics_: UpdatePatientDemographics = Field(None, alias="Demographics")
    Identifiers_: List[UpdatePatientIdentifier] = Field(..., alias="Identifiers")
    Notes_: List[str] = Field(None, alias="Notes")


class UpdatePatientAllergy(RedoxAbstractModel):
    AltCodes_: List[UpdatePatientAllergyAltCode] = Field(None, alias="AltCodes")
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Comment_: Union[str, None] = Field(None, alias="Comment")
    Criticality_: UpdatePatientAllergyCriticality = Field(None, alias="Criticality")
    EndDate_: Union[str, None] = Field(None, alias="EndDate")
    Name_: Union[str, None] = Field(None, alias="Name")
    Reaction_: List[UpdatePatientAllergyReaction] = Field(None, alias="Reaction")
    Severity_: UpdatePatientAllergySeverity = Field(None, alias="Severity")
    StartDate_: Union[str, None] = Field(None, alias="StartDate")
    Status_: UpdatePatientAllergyStatus = Field(None, alias="Status")
    Substance_: UpdatePatientAllergySubstance = Field(None, alias="Substance")


class UpdatePatientAllergyAltCode(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdatePatientAllergyCriticality(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdatePatientAllergyReaction(RedoxAbstractModel):
    AltCodes_: List[UpdatePatientAllergyReactionAltCode] = Field(None, alias="AltCodes")
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")
    Severity_: UpdatePatientAllergyReactionSeverity = Field(None, alias="Severity")
    Text_: Union[str, None] = Field(None, alias="Text")


class UpdatePatientAllergyReactionAltCode(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdatePatientAllergyReactionSeverity(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdatePatientAllergySeverity(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdatePatientAllergyStatus(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdatePatientAllergySubstance(RedoxAbstractModel):
    AltCodes_: List[UpdatePatientAllergySubstanceAltCode] = Field(
        None, alias="AltCodes"
    )
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdatePatientAllergySubstanceAltCode(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    CodeSystem_: Union[str, None] = Field(None, alias="CodeSystem")
    CodeSystemName_: Union[str, None] = Field(None, alias="CodeSystemName")
    Name_: Union[str, None] = Field(None, alias="Name")


class UpdatePatientDemographics(RedoxAbstractModel):
    Address_: UpdatePatientDemographicsAddress = Field(None, alias="Address")
    Citizenship_: List[str] = Field(None, alias="Citizenship")
    DOB_: Union[str, None] = Field(None, alias="DOB")
    DeathDateTime_: Union[str, None] = Field(None, alias="DeathDateTime")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    IsDeceased_: Union[bool, None] = Field(None, alias="IsDeceased")
    IsHispanic_: Union[bool, None] = Field(None, alias="IsHispanic")
    Language_: Union[str, None] = Field(None, alias="Language")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    MaritalStatus_: Union[str, None] = Field(None, alias="MaritalStatus")
    MiddleName_: Union[str, None] = Field(None, alias="MiddleName")
    PhoneNumber_: UpdatePatientDemographicsPhoneNumber = Field(
        None, alias="PhoneNumber"
    )
    Race_: Union[str, None] = Field(None, alias="Race")
    Religion_: Union[str, None] = Field(None, alias="Religion")
    SSN_: Union[str, None] = Field(None, alias="SSN")
    Sex_: Union[str, None] = Field(None, alias="Sex")


class UpdatePatientDemographicsAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdatePatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home_: Union[str, None] = Field(None, alias="Home")
    Mobile_: Union[str, None] = Field(None, alias="Mobile")
    Office_: Union[str, None] = Field(None, alias="Office")


class UpdatePatientIdentifier(RedoxAbstractModel):
    ID_: str = Field(..., alias="ID")
    IDType_: str = Field(..., alias="IDType")


class UpdateVisit(RedoxAbstractModel):
    AccountNumber_: Union[str, None] = Field(None, alias="AccountNumber")
    AttendingProvider_: UpdateVisitAttendingProvider = Field(
        None, alias="AttendingProvider"
    )
    Insurances_: List[UpdateVisitInsurance] = Field(None, alias="Insurances")
    Location_: UpdateVisitLocation = Field(None, alias="Location")
    PatientClass_: Union[str, None] = Field(None, alias="PatientClass")
    ReferringProvider_: UpdateVisitReferringProvider = Field(
        None, alias="ReferringProvider"
    )
    VisitDateTime_: Union[str, None] = Field(None, alias="VisitDateTime")
    VisitNumber_: Union[str, None] = Field(None, alias="VisitNumber")


class UpdateVisitAttendingProvider(RedoxAbstractModel):
    Address_: UpdateVisitAttendingProviderAddress = Field(None, alias="Address")
    Credentials_: List[str] = Field(None, alias="Credentials")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    Location_: UpdateVisitAttendingProviderLocation = Field(None, alias="Location")
    PhoneNumber_: UpdateVisitAttendingProviderPhoneNumber = Field(
        None, alias="PhoneNumber"
    )


class UpdateVisitAttendingProviderAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdateVisitAttendingProviderLocation(RedoxAbstractModel):
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[
        UpdateVisitAttendingProviderLocationDepartmentIdentifier
    ] = Field(None, alias="DepartmentIdentifiers")
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[
        UpdateVisitAttendingProviderLocationFacilityIdentifier
    ] = Field(None, alias="FacilityIdentifiers")
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class UpdateVisitAttendingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateVisitAttendingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateVisitAttendingProviderPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


class UpdateVisitInsurance(RedoxAbstractModel):
    AgreementType_: Union[str, None] = Field(None, alias="AgreementType")
    Company_: UpdateVisitInsuranceCompany = Field(None, alias="Company")
    CoverageType_: Union[str, None] = Field(None, alias="CoverageType")
    EffectiveDate_: Union[str, None] = Field(None, alias="EffectiveDate")
    ExpirationDate_: Union[str, None] = Field(None, alias="ExpirationDate")
    GroupName_: Union[str, None] = Field(None, alias="GroupName")
    GroupNumber_: Union[str, None] = Field(None, alias="GroupNumber")
    Insured_: UpdateVisitInsuranceInsured = Field(None, alias="Insured")
    MemberNumber_: Union[str, None] = Field(None, alias="MemberNumber")
    Plan_: UpdateVisitInsurancePlan = Field(None, alias="Plan")
    PolicyNumber_: Union[str, None] = Field(None, alias="PolicyNumber")
    Priority_: Union[str, None] = Field(None, alias="Priority")


class UpdateVisitInsuranceCompany(RedoxAbstractModel):
    Address_: UpdateVisitInsuranceCompanyAddress = Field(None, alias="Address")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    Name_: Union[str, None] = Field(None, alias="Name")
    PhoneNumber_: Union[str, None] = Field(None, alias="PhoneNumber")


class UpdateVisitInsuranceCompanyAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdateVisitInsuranceInsured(RedoxAbstractModel):
    Address_: UpdateVisitInsuranceInsuredAddress = Field(None, alias="Address")
    DOB_: Union[str, None] = Field(None, alias="DOB")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    Identifiers_: List[UpdateVisitInsuranceInsuredIdentifier] = Field(
        None, alias="Identifiers"
    )
    LastName_: Union[str, None] = Field(None, alias="LastName")
    MiddleName_: Union[str, None] = Field(None, alias="MiddleName")
    Relationship_: Union[str, None] = Field(None, alias="Relationship")
    SSN_: Union[str, None] = Field(None, alias="SSN")
    Sex_: Union[str, None] = Field(None, alias="Sex")


class UpdateVisitInsuranceInsuredAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdateVisitInsuranceInsuredIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateVisitInsurancePlan(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    Name_: Union[str, None] = Field(None, alias="Name")
    Type_: Union[str, None] = Field(None, alias="Type")


class UpdateVisitLocation(RedoxAbstractModel):
    Bed_: Union[str, None] = Field(None, alias="Bed")
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[UpdateVisitLocationDepartmentIdentifier] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[UpdateVisitLocationFacilityIdentifier] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class UpdateVisitLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateVisitLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateVisitReferringProvider(RedoxAbstractModel):
    Address_: UpdateVisitReferringProviderAddress = Field(None, alias="Address")
    Credentials_: List[str] = Field(None, alias="Credentials")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    Location_: UpdateVisitReferringProviderLocation = Field(None, alias="Location")
    PhoneNumber_: UpdateVisitReferringProviderPhoneNumber = Field(
        None, alias="PhoneNumber"
    )


class UpdateVisitReferringProviderAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class UpdateVisitReferringProviderLocation(RedoxAbstractModel):
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[
        UpdateVisitReferringProviderLocationDepartmentIdentifier
    ] = Field(None, alias="DepartmentIdentifiers")
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[
        UpdateVisitReferringProviderLocationFacilityIdentifier
    ] = Field(None, alias="FacilityIdentifiers")
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class UpdateVisitReferringProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateVisitReferringProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class UpdateVisitReferringProviderPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


Update.model_rebuild()
UpdateMeta.model_rebuild()
UpdateOrder.model_rebuild()
UpdateOrderEnteredBy.model_rebuild()
UpdateOrderEnteredByLocation.model_rebuild()
UpdateOrderMedication.model_rebuild()
UpdateOrderMedicationComponent.model_rebuild()
UpdateOrderMedicationProduct.model_rebuild()
UpdateOrderMedicationRoute.model_rebuild()
UpdateOrderPharmacy.model_rebuild()
UpdateOrderProvider.model_rebuild()
UpdateOrderProviderLocation.model_rebuild()
UpdateOrderVerifiedBy.model_rebuild()
UpdateOrderVerifiedByLocation.model_rebuild()
UpdatePatient.model_rebuild()
UpdatePatientAllergy.model_rebuild()
UpdatePatientAllergyReaction.model_rebuild()
UpdatePatientAllergySubstance.model_rebuild()
UpdatePatientDemographics.model_rebuild()
UpdateVisit.model_rebuild()
UpdateVisitAttendingProvider.model_rebuild()
UpdateVisitAttendingProviderLocation.model_rebuild()
UpdateVisitInsurance.model_rebuild()
UpdateVisitInsuranceCompany.model_rebuild()
UpdateVisitInsuranceInsured.model_rebuild()
UpdateVisitLocation.model_rebuild()
UpdateVisitReferringProvider.model_rebuild()
UpdateVisitReferringProviderLocation.model_rebuild()
