# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class Activate(EventTypeAbstractModel):
    Meta: "ActivateMeta" = Field(..., alias="Meta")
    Providers: list["ActivateProvider"] = Field(..., alias="Providers")


class ActivateMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["ActivateMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["ActivateMetaLog"] = Field(None, alias="Logs")
    Source: "ActivateMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class ActivateMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class ActivateMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class ActivateMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class ActivateProvider(RedoxAbstractModel):
    Demographics: "ActivateProviderDemographics" = Field(None, alias="Demographics")
    Identifiers: list["ActivateProviderIdentifier"] = Field(..., alias="Identifiers")
    Qualifications: list["ActivateProviderQualification"] = Field(None, alias="Qualifications")
    Roles: list["ActivateProviderRole"] = Field(None, alias="Roles")


class ActivateProviderDemographics(RedoxAbstractModel):
    Addresses: list["ActivateProviderDemographicsAddress"] = Field(None, alias="Addresses")
    Credentials: list[str] = Field(None, alias="Credentials")
    DOB: str | None = Field(None, alias="DOB")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    Languages: list[str] = Field(None, alias="Languages")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "ActivateProviderDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Sex: str | None = Field(None, alias="Sex")


class ActivateProviderDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    Use: str | None = Field(None, alias="Use")
    ZIP: str | None = Field(None, alias="ZIP")


class ActivateProviderDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class ActivateProviderIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ActivateProviderQualification(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    EndDate: str | None = Field(None, alias="EndDate")
    Identifiers: list["ActivateProviderQualificationIdentifier"] = Field(None, alias="Identifiers")
    StartDate: str | None = Field(None, alias="StartDate")


class ActivateProviderQualificationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ActivateProviderRole(RedoxAbstractModel):
    Availability: list["ActivateProviderRoleAvailability"] = Field(None, alias="Availability")
    Identifiers: list["ActivateProviderRoleIdentifier"] = Field(None, alias="Identifiers")
    Locations: list["ActivateProviderRoleLocation"] = Field(None, alias="Locations")
    Organization: "ActivateProviderRoleOrganization" = Field(None, alias="Organization")
    Services: list["ActivateProviderRoleService"] = Field(None, alias="Services")
    Specialties: list["ActivateProviderRoleSpecialty"] = Field(None, alias="Specialties")


class ActivateProviderRoleAvailability(RedoxAbstractModel):
    AvailableEndTime: str | None = Field(None, alias="AvailableEndTime")
    AvailableStartTime: str | None = Field(None, alias="AvailableStartTime")
    Days: list[str] = Field(None, alias="Days")


class ActivateProviderRoleIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ActivateProviderRoleLocation(RedoxAbstractModel):
    Address: "ActivateProviderRoleLocationAddress" = Field(None, alias="Address")
    Description: str | None = Field(None, alias="Description")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    Identifiers: list["ActivateProviderRoleLocationIdentifier"] = Field(None, alias="Identifiers")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: "ActivateProviderRoleLocationPhoneNumber" = Field(None, alias="PhoneNumber")
    Status: str | None = Field(None, alias="Status")


class ActivateProviderRoleLocationAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ActivateProviderRoleLocationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ActivateProviderRoleLocationPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class ActivateProviderRoleOrganization(RedoxAbstractModel):
    Address: "ActivateProviderRoleOrganizationAddress" = Field(None, alias="Address")
    Identifiers: list["ActivateProviderRoleOrganizationIdentifier"] = Field(None, alias="Identifiers")
    IsActive: str | None = Field(None, alias="IsActive")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class ActivateProviderRoleOrganizationAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class ActivateProviderRoleOrganizationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ActivateProviderRoleService(RedoxAbstractModel):
    Description: str | None = Field(None, alias="Description")
    Identifiers: list["ActivateProviderRoleServiceIdentifier"] = Field(None, alias="Identifiers")
    PhoneNumber: "ActivateProviderRoleServicePhoneNumber" = Field(None, alias="PhoneNumber")
    Type: str | None = Field(None, alias="Type")


class ActivateProviderRoleServiceIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class ActivateProviderRoleServicePhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class ActivateProviderRoleSpecialty(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


Activate.model_rebuild()
ActivateMeta.model_rebuild()
ActivateProvider.model_rebuild()
ActivateProviderDemographics.model_rebuild()
ActivateProviderQualification.model_rebuild()
ActivateProviderRole.model_rebuild()
ActivateProviderRoleLocation.model_rebuild()
ActivateProviderRoleOrganization.model_rebuild()
ActivateProviderRoleService.model_rebuild()
