# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class Deactivate(EventTypeAbstractModel):
    Meta: "DeactivateMeta" = Field(..., alias="Meta")
    Providers: list["DeactivateProvider"] = Field(..., alias="Providers")


class DeactivateMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["DeactivateMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["DeactivateMetaLog"] = Field(None, alias="Logs")
    Source: "DeactivateMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class DeactivateMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class DeactivateMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class DeactivateMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class DeactivateProvider(RedoxAbstractModel):
    Demographics: "DeactivateProviderDemographics" = Field(None, alias="Demographics")
    Identifiers: list["DeactivateProviderIdentifier"] = Field(..., alias="Identifiers")
    Qualifications: list["DeactivateProviderQualification"] = Field(None, alias="Qualifications")
    Roles: list["DeactivateProviderRole"] = Field(None, alias="Roles")


class DeactivateProviderDemographics(RedoxAbstractModel):
    Addresses: list["DeactivateProviderDemographicsAddress"] = Field(None, alias="Addresses")
    Credentials: list[str] = Field(None, alias="Credentials")
    DOB: str | None = Field(None, alias="DOB")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    Languages: list[str] = Field(None, alias="Languages")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "DeactivateProviderDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Sex: str | None = Field(None, alias="Sex")


class DeactivateProviderDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    Use: str | None = Field(None, alias="Use")
    ZIP: str | None = Field(None, alias="ZIP")


class DeactivateProviderDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class DeactivateProviderIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DeactivateProviderQualification(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    EndDate: str | None = Field(None, alias="EndDate")
    Identifiers: list["DeactivateProviderQualificationIdentifier"] = Field(None, alias="Identifiers")
    StartDate: str | None = Field(None, alias="StartDate")


class DeactivateProviderQualificationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DeactivateProviderRole(RedoxAbstractModel):
    Availability: list["DeactivateProviderRoleAvailability"] = Field(None, alias="Availability")
    Identifiers: list["DeactivateProviderRoleIdentifier"] = Field(None, alias="Identifiers")
    Locations: list["DeactivateProviderRoleLocation"] = Field(None, alias="Locations")
    Organization: "DeactivateProviderRoleOrganization" = Field(None, alias="Organization")
    Services: list["DeactivateProviderRoleService"] = Field(None, alias="Services")
    Specialties: list["DeactivateProviderRoleSpecialty"] = Field(None, alias="Specialties")


class DeactivateProviderRoleAvailability(RedoxAbstractModel):
    AvailableEndTime: str | None = Field(None, alias="AvailableEndTime")
    AvailableStartTime: str | None = Field(None, alias="AvailableStartTime")
    Days: list[str] = Field(None, alias="Days")


class DeactivateProviderRoleIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DeactivateProviderRoleLocation(RedoxAbstractModel):
    Address: "DeactivateProviderRoleLocationAddress" = Field(None, alias="Address")
    Description: str | None = Field(None, alias="Description")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    Identifiers: list["DeactivateProviderRoleLocationIdentifier"] = Field(None, alias="Identifiers")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: "DeactivateProviderRoleLocationPhoneNumber" = Field(None, alias="PhoneNumber")
    Status: str | None = Field(None, alias="Status")


class DeactivateProviderRoleLocationAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class DeactivateProviderRoleLocationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DeactivateProviderRoleLocationPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class DeactivateProviderRoleOrganization(RedoxAbstractModel):
    Address: "DeactivateProviderRoleOrganizationAddress" = Field(None, alias="Address")
    Identifiers: list["DeactivateProviderRoleOrganizationIdentifier"] = Field(None, alias="Identifiers")
    IsActive: str | None = Field(None, alias="IsActive")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class DeactivateProviderRoleOrganizationAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class DeactivateProviderRoleOrganizationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DeactivateProviderRoleService(RedoxAbstractModel):
    Description: str | None = Field(None, alias="Description")
    Identifiers: list["DeactivateProviderRoleServiceIdentifier"] = Field(None, alias="Identifiers")
    PhoneNumber: "DeactivateProviderRoleServicePhoneNumber" = Field(None, alias="PhoneNumber")
    Type: str | None = Field(None, alias="Type")


class DeactivateProviderRoleServiceIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DeactivateProviderRoleServicePhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class DeactivateProviderRoleSpecialty(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


Deactivate.model_rebuild()
DeactivateMeta.model_rebuild()
DeactivateProvider.model_rebuild()
DeactivateProviderDemographics.model_rebuild()
DeactivateProviderQualification.model_rebuild()
DeactivateProviderRole.model_rebuild()
DeactivateProviderRoleLocation.model_rebuild()
DeactivateProviderRoleOrganization.model_rebuild()
DeactivateProviderRoleService.model_rebuild()
