# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #
from __future__ import annotations

from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class Update(EventTypeAbstractModel):
    Meta: UpdateMeta = Field(..., alias="Meta")
    Providers: list[UpdateProvider] = Field(..., alias="Providers")


class UpdateMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list[UpdateMetaDestination] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list[UpdateMetaLog] = Field(None, alias="Logs")
    Source: UpdateMetaSource = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class UpdateMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class UpdateMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class UpdateMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class UpdateProvider(RedoxAbstractModel):
    Demographics: UpdateProviderDemographics = Field(None, alias="Demographics")
    Identifiers: list[UpdateProviderIdentifier] = Field(..., alias="Identifiers")
    IsActive: bool = Field(..., alias="IsActive")
    Qualifications: list[UpdateProviderQualification] = Field(None, alias="Qualifications")
    Roles: list[UpdateProviderRole] = Field(None, alias="Roles")


class UpdateProviderDemographics(RedoxAbstractModel):
    Addresses: list[UpdateProviderDemographicsAddress] = Field(None, alias="Addresses")
    Credentials: list[str] = Field(None, alias="Credentials")
    DOB: str | None = Field(None, alias="DOB")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    Languages: list[str] = Field(None, alias="Languages")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: UpdateProviderDemographicsPhoneNumber = Field(None, alias="PhoneNumber")
    Sex: str | None = Field(None, alias="Sex")


class UpdateProviderDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    Use: str | None = Field(None, alias="Use")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateProviderDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class UpdateProviderIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateProviderQualification(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    EndDate: str | None = Field(None, alias="EndDate")
    Identifiers: list[UpdateProviderQualificationIdentifier] = Field(None, alias="Identifiers")
    StartDate: str | None = Field(None, alias="StartDate")


class UpdateProviderQualificationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateProviderRole(RedoxAbstractModel):
    Availability: list[UpdateProviderRoleAvailability] = Field(None, alias="Availability")
    Identifiers: list[UpdateProviderRoleIdentifier] = Field(None, alias="Identifiers")
    Locations: list[UpdateProviderRoleLocation] = Field(None, alias="Locations")
    Organization: UpdateProviderRoleOrganization = Field(None, alias="Organization")
    Services: list[UpdateProviderRoleService] = Field(None, alias="Services")
    Specialties: list[UpdateProviderRoleSpecialty] = Field(None, alias="Specialties")


class UpdateProviderRoleAvailability(RedoxAbstractModel):
    AvailableEndTime: str | None = Field(None, alias="AvailableEndTime")
    AvailableStartTime: str | None = Field(None, alias="AvailableStartTime")
    Days: list[str] = Field(None, alias="Days")


class UpdateProviderRoleIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateProviderRoleLocation(RedoxAbstractModel):
    Address: UpdateProviderRoleLocationAddress = Field(None, alias="Address")
    Description: str | None = Field(None, alias="Description")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    Identifiers: list[UpdateProviderRoleLocationIdentifier] = Field(None, alias="Identifiers")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: UpdateProviderRoleLocationPhoneNumber = Field(None, alias="PhoneNumber")
    Status: str | None = Field(None, alias="Status")


class UpdateProviderRoleLocationAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateProviderRoleLocationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateProviderRoleLocationPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class UpdateProviderRoleOrganization(RedoxAbstractModel):
    Address: UpdateProviderRoleOrganizationAddress = Field(None, alias="Address")
    Identifiers: list[UpdateProviderRoleOrganizationIdentifier] = Field(None, alias="Identifiers")
    IsActive: str | None = Field(None, alias="IsActive")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class UpdateProviderRoleOrganizationAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateProviderRoleOrganizationIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateProviderRoleService(RedoxAbstractModel):
    Description: str | None = Field(None, alias="Description")
    Identifiers: list[UpdateProviderRoleServiceIdentifier] = Field(None, alias="Identifiers")
    PhoneNumber: UpdateProviderRoleServicePhoneNumber = Field(None, alias="PhoneNumber")
    Type: str | None = Field(None, alias="Type")


class UpdateProviderRoleServiceIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateProviderRoleServicePhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class UpdateProviderRoleSpecialty(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


Update.model_rebuild()
UpdateMeta.model_rebuild()
UpdateProvider.model_rebuild()
UpdateProviderDemographics.model_rebuild()
UpdateProviderQualification.model_rebuild()
UpdateProviderRole.model_rebuild()
UpdateProviderRoleLocation.model_rebuild()
UpdateProviderRoleOrganization.model_rebuild()
UpdateProviderRoleService.model_rebuild()
