# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class Deplete(EventTypeAbstractModel):
    Items: list["DepleteItem"] = Field(..., alias="Items")
    Meta: "DepleteMeta" = Field(..., alias="Meta")
    Patient: "DepletePatient" = Field(None, alias="Patient")
    Visit: "DepleteVisit" = Field(None, alias="Visit")


class DepleteItem(RedoxAbstractModel):
    Description: str | None = Field(None, alias="Description")
    Identifiers: list["DepleteItemIdentifier"] = Field(..., alias="Identifiers")
    Location: "DepleteItemLocation" = Field(None, alias="Location")
    LotNumber: str | None = Field(None, alias="LotNumber")
    Notes: str | None = Field(None, alias="Notes")
    OrderingProvider: "DepleteItemOrderingProvider" = Field(None, alias="OrderingProvider")
    Procedure: "DepleteItemProcedure" = Field(None, alias="Procedure")
    Quantity: float | None = Field(None, alias="Quantity")
    SerialNumber: str | None = Field(None, alias="SerialNumber")
    Type: str | None = Field(None, alias="Type")
    Units: str | None = Field(None, alias="Units")
    UsedQuantity: float | None = Field(None, alias="UsedQuantity")
    Vendor: "DepleteItemVendor" = Field(None, alias="Vendor")
    WastedQuantity: float | None = Field(None, alias="WastedQuantity")


class DepleteItemIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str = Field(..., alias="IDType")


class DepleteItemLocation(RedoxAbstractModel):
    Bin: str | None = Field(None, alias="Bin")
    Department: str | None = Field(None, alias="Department")
    Facility: str | None = Field(None, alias="Facility")
    ID: str | None = Field(None, alias="ID")


class DepleteItemOrderingProvider(RedoxAbstractModel):
    Address: "DepleteItemOrderingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "DepleteItemOrderingProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "DepleteItemOrderingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class DepleteItemOrderingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class DepleteItemOrderingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["DepleteItemOrderingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["DepleteItemOrderingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class DepleteItemOrderingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DepleteItemOrderingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DepleteItemOrderingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class DepleteItemProcedure(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Modifier: str | None = Field(None, alias="Modifier")


class DepleteItemVendor(RedoxAbstractModel):
    CatalogNumber: str | None = Field(None, alias="CatalogNumber")
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class DepleteMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["DepleteMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["DepleteMetaLog"] = Field(None, alias="Logs")
    Source: "DepleteMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class DepleteMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class DepleteMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class DepleteMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class DepletePatient(RedoxAbstractModel):
    Demographics: "DepletePatientDemographics" = Field(None, alias="Demographics")
    Identifiers: list["DepletePatientIdentifier"] = Field(None, alias="Identifiers")
    Notes: list[str] = Field(None, alias="Notes")


class DepletePatientDemographics(RedoxAbstractModel):
    Address: "DepletePatientDemographicsAddress" = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "DepletePatientDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class DepletePatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class DepletePatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class DepletePatientIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class DepleteVisit(RedoxAbstractModel):
    VisitNumber: str | None = Field(None, alias="VisitNumber")


Deplete.model_rebuild()
DepleteItem.model_rebuild()
DepleteItemOrderingProvider.model_rebuild()
DepleteItemOrderingProviderLocation.model_rebuild()
DepleteMeta.model_rebuild()
DepletePatient.model_rebuild()
DepletePatientDemographics.model_rebuild()
