# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class Update(EventTypeAbstractModel):
    Meta: "UpdateMeta" = Field(..., alias="Meta")
    Order: "UpdateOrder" = Field(..., alias="Order")
    Patient: "UpdatePatient" = Field(..., alias="Patient")
    Visit: "UpdateVisit" = Field(None, alias="Visit")


class UpdateMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["UpdateMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["UpdateMetaLog"] = Field(None, alias="Logs")
    Source: "UpdateMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class UpdateMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class UpdateMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class UpdateMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class UpdateOrder(RedoxAbstractModel):
    ApplicationOrderID: str | None = Field(None, alias="ApplicationOrderID")
    ClinicalInfo: list["UpdateOrderClinicalInfo"] = Field(None, alias="ClinicalInfo")
    CollectionDateTime: str | None = Field(None, alias="CollectionDateTime")
    Comments: str | None = Field(None, alias="Comments")
    Diagnoses: list["UpdateOrderDiagnosis"] = Field(None, alias="Diagnoses")
    Expiration: str | None = Field(None, alias="Expiration")
    ID: str = Field(..., alias="ID")
    Notes: list[str] = Field(None, alias="Notes")
    OrderingFacility: "UpdateOrderOrderingFacility" = Field(None, alias="OrderingFacility")
    Priority: str | None = Field(None, alias="Priority")
    Procedure: "UpdateOrderProcedure" = Field(None, alias="Procedure")
    Provider: "UpdateOrderProvider" = Field(None, alias="Provider")
    ResultCopyProviders: list["UpdateOrderResultCopyProvider"] = Field(None, alias="ResultCopyProviders")
    Specimen: "UpdateOrderSpecimen" = Field(None, alias="Specimen")
    Status: str | None = Field(None, alias="Status")
    TransactionDateTime: str | None = Field(None, alias="TransactionDateTime")


class UpdateOrderClinicalInfo(RedoxAbstractModel):
    Abbreviation: str | None = Field(None, alias="Abbreviation")
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    Notes: list[str] = Field(None, alias="Notes")
    Units: str | None = Field(None, alias="Units")
    Value: str | None = Field(None, alias="Value")


class UpdateOrderDiagnosis(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    DocumentedDateTime: str | None = Field(None, alias="DocumentedDateTime")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class UpdateOrderOrderingFacility(RedoxAbstractModel):
    Address: "UpdateOrderOrderingFacilityAddress" = Field(None, alias="Address")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class UpdateOrderOrderingFacilityAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateOrderProcedure(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


class UpdateOrderProvider(RedoxAbstractModel):
    Address: "UpdateOrderProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "UpdateOrderProviderLocation" = Field(None, alias="Location")
    NPI: str | None = Field(None, alias="NPI")
    PhoneNumber: "UpdateOrderProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class UpdateOrderProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateOrderProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["UpdateOrderProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["UpdateOrderProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class UpdateOrderProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateOrderProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateOrderProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class UpdateOrderResultCopyProvider(RedoxAbstractModel):
    Address: "UpdateOrderResultCopyProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "UpdateOrderResultCopyProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "UpdateOrderResultCopyProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class UpdateOrderResultCopyProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateOrderResultCopyProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["UpdateOrderResultCopyProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["UpdateOrderResultCopyProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class UpdateOrderResultCopyProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateOrderResultCopyProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateOrderResultCopyProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class UpdateOrderSpecimen(RedoxAbstractModel):
    BodySite: str | None = Field(None, alias="BodySite")
    ID: str | None = Field(None, alias="ID")
    Source: str | None = Field(None, alias="Source")


class UpdatePatient(RedoxAbstractModel):
    Demographics: "UpdatePatientDemographics" = Field(None, alias="Demographics")
    Identifiers: list["UpdatePatientIdentifier"] = Field(..., alias="Identifiers")
    Notes: list[str] = Field(None, alias="Notes")


class UpdatePatientDemographics(RedoxAbstractModel):
    Address: "UpdatePatientDemographicsAddress" = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "UpdatePatientDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class UpdatePatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdatePatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class UpdatePatientIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str = Field(..., alias="IDType")


class UpdateVisit(RedoxAbstractModel):
    AccountNumber: str | None = Field(None, alias="AccountNumber")
    AttendingProvider: "UpdateVisitAttendingProvider" = Field(None, alias="AttendingProvider")
    ConsultingProvider: "UpdateVisitConsultingProvider" = Field(None, alias="ConsultingProvider")
    Guarantor: "UpdateVisitGuarantor" = Field(None, alias="Guarantor")
    Insurances: list["UpdateVisitInsurance"] = Field(None, alias="Insurances")
    Location: "UpdateVisitLocation" = Field(None, alias="Location")
    PatientClass: str | None = Field(None, alias="PatientClass")
    ReferringProvider: "UpdateVisitReferringProvider" = Field(None, alias="ReferringProvider")
    VisitDateTime: str | None = Field(None, alias="VisitDateTime")
    VisitNumber: str | None = Field(None, alias="VisitNumber")


class UpdateVisitAttendingProvider(RedoxAbstractModel):
    Address: "UpdateVisitAttendingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "UpdateVisitAttendingProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "UpdateVisitAttendingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class UpdateVisitAttendingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateVisitAttendingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["UpdateVisitAttendingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["UpdateVisitAttendingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class UpdateVisitAttendingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitAttendingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitAttendingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class UpdateVisitConsultingProvider(RedoxAbstractModel):
    Address: "UpdateVisitConsultingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "UpdateVisitConsultingProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "UpdateVisitConsultingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class UpdateVisitConsultingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateVisitConsultingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["UpdateVisitConsultingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["UpdateVisitConsultingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class UpdateVisitConsultingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitConsultingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitConsultingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class UpdateVisitGuarantor(RedoxAbstractModel):
    Address: "UpdateVisitGuarantorAddress" = Field(None, alias="Address")
    DOB: str | None = Field(None, alias="DOB")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    Employer: "UpdateVisitGuarantorEmployer" = Field(None, alias="Employer")
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    Number: str | None = Field(None, alias="Number")
    PhoneNumber: "UpdateVisitGuarantorPhoneNumber" = Field(None, alias="PhoneNumber")
    RelationToPatient: str | None = Field(None, alias="RelationToPatient")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")
    Spouse: "UpdateVisitGuarantorSpouse" = Field(None, alias="Spouse")
    Type: str | None = Field(None, alias="Type")


class UpdateVisitGuarantorAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateVisitGuarantorEmployer(RedoxAbstractModel):
    Address: "UpdateVisitGuarantorEmployerAddress" = Field(None, alias="Address")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class UpdateVisitGuarantorEmployerAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateVisitGuarantorPhoneNumber(RedoxAbstractModel):
    Business: str | None = Field(None, alias="Business")
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")


class UpdateVisitGuarantorSpouse(RedoxAbstractModel):
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")


class UpdateVisitInsurance(RedoxAbstractModel):
    AgreementType: str | None = Field(None, alias="AgreementType")
    Company: "UpdateVisitInsuranceCompany" = Field(None, alias="Company")
    CoverageType: str | None = Field(None, alias="CoverageType")
    EffectiveDate: str | None = Field(None, alias="EffectiveDate")
    ExpirationDate: str | None = Field(None, alias="ExpirationDate")
    GroupName: str | None = Field(None, alias="GroupName")
    GroupNumber: str | None = Field(None, alias="GroupNumber")
    Insured: "UpdateVisitInsuranceInsured" = Field(None, alias="Insured")
    MemberNumber: str | None = Field(None, alias="MemberNumber")
    Plan: "UpdateVisitInsurancePlan" = Field(None, alias="Plan")
    PolicyNumber: str | None = Field(None, alias="PolicyNumber")
    Priority: str | None = Field(None, alias="Priority")


class UpdateVisitInsuranceCompany(RedoxAbstractModel):
    Address: "UpdateVisitInsuranceCompanyAddress" = Field(None, alias="Address")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class UpdateVisitInsuranceCompanyAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateVisitInsuranceInsured(RedoxAbstractModel):
    Address: "UpdateVisitInsuranceInsuredAddress" = Field(None, alias="Address")
    DOB: str | None = Field(None, alias="DOB")
    FirstName: str | None = Field(None, alias="FirstName")
    Identifiers: list["UpdateVisitInsuranceInsuredIdentifier"] = Field(None, alias="Identifiers")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    Relationship: str | None = Field(None, alias="Relationship")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class UpdateVisitInsuranceInsuredAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateVisitInsuranceInsuredIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitInsurancePlan(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class UpdateVisitLocation(RedoxAbstractModel):
    Bed: str | None = Field(None, alias="Bed")
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["UpdateVisitLocationDepartmentIdentifier"] = Field(None, alias="DepartmentIdentifiers")
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["UpdateVisitLocationFacilityIdentifier"] = Field(None, alias="FacilityIdentifiers")
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class UpdateVisitLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitReferringProvider(RedoxAbstractModel):
    Address: "UpdateVisitReferringProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "UpdateVisitReferringProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "UpdateVisitReferringProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class UpdateVisitReferringProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class UpdateVisitReferringProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["UpdateVisitReferringProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["UpdateVisitReferringProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class UpdateVisitReferringProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitReferringProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class UpdateVisitReferringProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


Update.model_rebuild()
UpdateMeta.model_rebuild()
UpdateOrder.model_rebuild()
UpdateOrderOrderingFacility.model_rebuild()
UpdateOrderProvider.model_rebuild()
UpdateOrderProviderLocation.model_rebuild()
UpdateOrderResultCopyProvider.model_rebuild()
UpdateOrderResultCopyProviderLocation.model_rebuild()
UpdatePatient.model_rebuild()
UpdatePatientDemographics.model_rebuild()
UpdateVisit.model_rebuild()
UpdateVisitAttendingProvider.model_rebuild()
UpdateVisitAttendingProviderLocation.model_rebuild()
UpdateVisitConsultingProvider.model_rebuild()
UpdateVisitConsultingProviderLocation.model_rebuild()
UpdateVisitGuarantor.model_rebuild()
UpdateVisitGuarantorEmployer.model_rebuild()
UpdateVisitInsurance.model_rebuild()
UpdateVisitInsuranceCompany.model_rebuild()
UpdateVisitInsuranceInsured.model_rebuild()
UpdateVisitLocation.model_rebuild()
UpdateVisitReferringProvider.model_rebuild()
UpdateVisitReferringProviderLocation.model_rebuild()
