# -*- coding: utf-8 -*-
# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #

from __future__ import annotations

from typing import List, Union

from pydantic import Field

from ..abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class AuthResponse(EventTypeAbstractModel):
    Authorization_: AuthResponseAuthorization = Field(None, alias="Authorization")
    Meta_: AuthResponseMeta = Field(..., alias="Meta")
    Patient_: AuthResponsePatient = Field(..., alias="Patient")
    Referral_: AuthResponseReferral = Field(None, alias="Referral")


class AuthResponseAuthorization(RedoxAbstractModel):
    AdditionalDates_: List[AuthResponseAuthorizationAdditionalDate] = Field(
        None, alias="AdditionalDates"
    )
    AdmissionSource_: Union[str, None] = Field(None, alias="AdmissionSource")
    AdmissionType_: Union[str, None] = Field(None, alias="AdmissionType")
    AlternateID_: Union[str, None] = Field(None, alias="AlternateID")
    Category_: Union[str, None] = Field(None, alias="Category")
    CertificationCode_: Union[str, None] = Field(None, alias="CertificationCode")
    Decision_: Union[str, None] = Field(None, alias="Decision")
    DecisionReason_: Union[str, None] = Field(None, alias="DecisionReason")
    Diagnoses_: List[AuthResponseAuthorizationDiagnosis] = Field(
        None, alias="Diagnoses"
    )
    EffectiveDate_: Union[str, None] = Field(None, alias="EffectiveDate")
    EventDate_: Union[str, None] = Field(None, alias="EventDate")
    ExpirationDate_: Union[str, None] = Field(None, alias="ExpirationDate")
    IssueDate_: Union[str, None] = Field(None, alias="IssueDate")
    Notes_: List[str] = Field(None, alias="Notes")
    Number_: Union[str, None] = Field(None, alias="Number")
    Providers_: List[AuthResponseAuthorizationProvider] = Field(None, alias="Providers")
    Quantity_: AuthResponseAuthorizationQuantity = Field(None, alias="Quantity")
    RelatedCause_: Union[str, None] = Field(None, alias="RelatedCause")
    Request_: AuthResponseAuthorizationRequest = Field(None, alias="Request")
    ServiceLevel_: Union[str, None] = Field(None, alias="ServiceLevel")
    ServiceLocation_: Union[str, None] = Field(None, alias="ServiceLocation")
    ServiceType_: Union[str, None] = Field(None, alias="ServiceType")
    Services_: List[AuthResponseAuthorizationService] = Field(None, alias="Services")
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseAuthorizationAdditionalDate(RedoxAbstractModel):
    DateTime_: Union[str, None] = Field(None, alias="DateTime")
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseAuthorizationDiagnosis(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    Codeset_: Union[str, None] = Field(None, alias="Codeset")
    DocumentedDateTime_: Union[str, None] = Field(None, alias="DocumentedDateTime")
    Name_: Union[str, None] = Field(None, alias="Name")
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseAuthorizationProvider(RedoxAbstractModel):
    Address_: AuthResponseAuthorizationProviderAddress = Field(None, alias="Address")
    ContactInfo_: Union[str, None] = Field(None, alias="ContactInfo")
    Credentials_: List[str] = Field(None, alias="Credentials")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    Location_: AuthResponseAuthorizationProviderLocation = Field(None, alias="Location")
    PhoneNumber_: AuthResponseAuthorizationProviderPhoneNumber = Field(
        None, alias="PhoneNumber"
    )
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseAuthorizationProviderAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class AuthResponseAuthorizationProviderLocation(RedoxAbstractModel):
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[
        AuthResponseAuthorizationProviderLocationDepartmentIdentifier
    ] = Field(None, alias="DepartmentIdentifiers")
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[
        AuthResponseAuthorizationProviderLocationFacilityIdentifier
    ] = Field(None, alias="FacilityIdentifiers")
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseAuthorizationProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class AuthResponseAuthorizationProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class AuthResponseAuthorizationProviderPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


class AuthResponseAuthorizationQuantity(RedoxAbstractModel):
    Units_: Union[str, None] = Field(None, alias="Units")
    Value_: Union[str, None] = Field(None, alias="Value")


class AuthResponseAuthorizationRequest(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class AuthResponseAuthorizationService(RedoxAbstractModel):
    AuthorizationNumber_: Union[str, None] = Field(None, alias="AuthorizationNumber")
    Code_: Union[str, None] = Field(None, alias="Code")
    Codeset_: Union[str, None] = Field(None, alias="Codeset")
    Decision_: Union[str, None] = Field(None, alias="Decision")
    DecisionReason_: Union[str, None] = Field(None, alias="DecisionReason")
    Description_: Union[str, None] = Field(None, alias="Description")
    EffectiveDate_: Union[str, None] = Field(None, alias="EffectiveDate")
    ExpirationDate_: Union[str, None] = Field(None, alias="ExpirationDate")
    IssueDate_: Union[str, None] = Field(None, alias="IssueDate")
    Modifiers_: List[str] = Field(None, alias="Modifiers")
    Notes_: List[str] = Field(None, alias="Notes")
    Quantity_: AuthResponseAuthorizationServiceQuantity = Field(None, alias="Quantity")
    RevenueCode_: Union[str, None] = Field(None, alias="RevenueCode")
    ServiceDate_: Union[str, None] = Field(None, alias="ServiceDate")


class AuthResponseAuthorizationServiceQuantity(RedoxAbstractModel):
    Units_: Union[str, None] = Field(None, alias="Units")
    Value_: Union[str, None] = Field(None, alias="Value")


class AuthResponseMeta(RedoxAbstractModel):
    DataModel_: str = Field(..., alias="DataModel")
    Destinations_: List[AuthResponseMetaDestination] = Field(None, alias="Destinations")
    EventDateTime_: Union[str, None] = Field(None, alias="EventDateTime")
    EventType_: str = Field(..., alias="EventType")
    FacilityCode_: Union[str, None] = Field(None, alias="FacilityCode")
    Logs_: List[AuthResponseMetaLog] = Field(None, alias="Logs")
    Message_: AuthResponseMetaMessage = Field(None, alias="Message")
    Source_: AuthResponseMetaSource = Field(None, alias="Source")
    Test_: Union[bool, None] = Field(None, alias="Test")
    Transmission_: AuthResponseMetaTransmission = Field(None, alias="Transmission")


class AuthResponseMetaDestination(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    Name_: Union[str, None] = Field(None, alias="Name")


class AuthResponseMetaLog(RedoxAbstractModel):
    AttemptID_: Union[str, None] = Field(None, alias="AttemptID")
    ID_: Union[str, None] = Field(None, alias="ID")


class AuthResponseMetaMessage(RedoxAbstractModel):
    ID_: Union[float, None] = Field(None, alias="ID")


class AuthResponseMetaSource(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    Name_: Union[str, None] = Field(None, alias="Name")


class AuthResponseMetaTransmission(RedoxAbstractModel):
    ID_: Union[float, None] = Field(None, alias="ID")


class AuthResponsePatient(RedoxAbstractModel):
    Contacts_: List[AuthResponsePatientContact] = Field(None, alias="Contacts")
    Demographics_: AuthResponsePatientDemographics = Field(None, alias="Demographics")
    Identifiers_: List[AuthResponsePatientIdentifier] = Field(..., alias="Identifiers")
    Insurances_: List[AuthResponsePatientInsurance] = Field(None, alias="Insurances")
    Notes_: List[str] = Field(None, alias="Notes")


class AuthResponsePatientContact(RedoxAbstractModel):
    Address_: AuthResponsePatientContactAddress = Field(None, alias="Address")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    MiddleName_: Union[str, None] = Field(None, alias="MiddleName")
    PhoneNumber_: AuthResponsePatientContactPhoneNumber = Field(
        None, alias="PhoneNumber"
    )
    RelationToPatient_: Union[str, None] = Field(None, alias="RelationToPatient")
    Roles_: List[str] = Field(None, alias="Roles")


class AuthResponsePatientContactAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class AuthResponsePatientContactPhoneNumber(RedoxAbstractModel):
    Home_: Union[str, None] = Field(None, alias="Home")
    Mobile_: Union[str, None] = Field(None, alias="Mobile")
    Office_: Union[str, None] = Field(None, alias="Office")


class AuthResponsePatientDemographics(RedoxAbstractModel):
    Address_: AuthResponsePatientDemographicsAddress = Field(None, alias="Address")
    Citizenship_: List[str] = Field(None, alias="Citizenship")
    DOB_: Union[str, None] = Field(None, alias="DOB")
    DeathDateTime_: Union[str, None] = Field(None, alias="DeathDateTime")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    IsDeceased_: Union[bool, None] = Field(None, alias="IsDeceased")
    IsHispanic_: Union[bool, None] = Field(None, alias="IsHispanic")
    Language_: Union[str, None] = Field(None, alias="Language")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    MaritalStatus_: Union[str, None] = Field(None, alias="MaritalStatus")
    MiddleName_: Union[str, None] = Field(None, alias="MiddleName")
    PhoneNumber_: AuthResponsePatientDemographicsPhoneNumber = Field(
        None, alias="PhoneNumber"
    )
    Race_: Union[str, None] = Field(None, alias="Race")
    Religion_: Union[str, None] = Field(None, alias="Religion")
    SSN_: Union[str, None] = Field(None, alias="SSN")
    Sex_: Union[str, None] = Field(None, alias="Sex")


class AuthResponsePatientDemographicsAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class AuthResponsePatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home_: Union[str, None] = Field(None, alias="Home")
    Mobile_: Union[str, None] = Field(None, alias="Mobile")
    Office_: Union[str, None] = Field(None, alias="Office")


class AuthResponsePatientIdentifier(RedoxAbstractModel):
    ID_: str = Field(..., alias="ID")
    IDType_: str = Field(..., alias="IDType")


class AuthResponsePatientInsurance(RedoxAbstractModel):
    AgreementType_: Union[str, None] = Field(None, alias="AgreementType")
    Company_: AuthResponsePatientInsuranceCompany = Field(None, alias="Company")
    CoverageType_: Union[str, None] = Field(None, alias="CoverageType")
    EffectiveDate_: Union[str, None] = Field(None, alias="EffectiveDate")
    ExpirationDate_: Union[str, None] = Field(None, alias="ExpirationDate")
    GroupName_: Union[str, None] = Field(None, alias="GroupName")
    GroupNumber_: Union[str, None] = Field(None, alias="GroupNumber")
    Insured_: AuthResponsePatientInsuranceInsured = Field(None, alias="Insured")
    MemberNumber_: Union[str, None] = Field(None, alias="MemberNumber")
    Plan_: AuthResponsePatientInsurancePlan = Field(None, alias="Plan")
    PolicyNumber_: Union[str, None] = Field(None, alias="PolicyNumber")
    Priority_: Union[str, None] = Field(None, alias="Priority")


class AuthResponsePatientInsuranceCompany(RedoxAbstractModel):
    Address_: AuthResponsePatientInsuranceCompanyAddress = Field(None, alias="Address")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    Name_: Union[str, None] = Field(None, alias="Name")
    PhoneNumber_: Union[str, None] = Field(None, alias="PhoneNumber")


class AuthResponsePatientInsuranceCompanyAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class AuthResponsePatientInsuranceInsured(RedoxAbstractModel):
    Address_: AuthResponsePatientInsuranceInsuredAddress = Field(None, alias="Address")
    DOB_: Union[str, None] = Field(None, alias="DOB")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    Identifiers_: List[AuthResponsePatientInsuranceInsuredIdentifier] = Field(
        None, alias="Identifiers"
    )
    LastName_: Union[str, None] = Field(None, alias="LastName")
    MiddleName_: Union[str, None] = Field(None, alias="MiddleName")
    Relationship_: Union[str, None] = Field(None, alias="Relationship")
    SSN_: Union[str, None] = Field(None, alias="SSN")
    Sex_: Union[str, None] = Field(None, alias="Sex")


class AuthResponsePatientInsuranceInsuredAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class AuthResponsePatientInsuranceInsuredIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class AuthResponsePatientInsurancePlan(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    Name_: Union[str, None] = Field(None, alias="Name")
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseReferral(RedoxAbstractModel):
    AlternateID_: Union[str, None] = Field(None, alias="AlternateID")
    Authorization_: AuthResponseReferralAuthorization = Field(
        None, alias="Authorization"
    )
    Category_: Union[str, None] = Field(None, alias="Category")
    DateTime_: Union[str, None] = Field(None, alias="DateTime")
    DepartmentSpecialty_: Union[str, None] = Field(None, alias="DepartmentSpecialty")
    Diagnoses_: List[AuthResponseReferralDiagnosis] = Field(None, alias="Diagnoses")
    ExpirationDateTime_: Union[str, None] = Field(None, alias="ExpirationDateTime")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    Notes_: List[str] = Field(None, alias="Notes")
    Priority_: Union[str, None] = Field(None, alias="Priority")
    Procedures_: List[AuthResponseReferralProcedure] = Field(None, alias="Procedures")
    ProcessDateTime_: Union[str, None] = Field(None, alias="ProcessDateTime")
    ProviderSpecialty_: Union[str, None] = Field(None, alias="ProviderSpecialty")
    Providers_: List[AuthResponseReferralProvider] = Field(None, alias="Providers")
    Reason_: Union[str, None] = Field(None, alias="Reason")
    RelatedCause_: Union[str, None] = Field(None, alias="RelatedCause")
    RequestType_: Union[str, None] = Field(None, alias="RequestType")
    ServiceLocation_: Union[str, None] = Field(None, alias="ServiceLocation")
    Status_: Union[str, None] = Field(None, alias="Status")
    StatusReason_: Union[str, None] = Field(None, alias="StatusReason")
    Type_: Union[str, None] = Field(None, alias="Type")
    Visit_: AuthResponseReferralVisit = Field(None, alias="Visit")


class AuthResponseReferralAuthorization(RedoxAbstractModel):
    AuthorizedTreatmentCount_: Union[str, None] = Field(
        None, alias="AuthorizedTreatmentCount"
    )
    Company_: AuthResponseReferralAuthorizationCompany = Field(None, alias="Company")
    DateTime_: Union[str, None] = Field(None, alias="DateTime")
    ExpirationDateTime_: Union[str, None] = Field(None, alias="ExpirationDateTime")
    Notes_: List[str] = Field(None, alias="Notes")
    Number_: Union[str, None] = Field(None, alias="Number")
    Plan_: AuthResponseReferralAuthorizationPlan = Field(None, alias="Plan")
    ReimbursementLimit_: Union[str, None] = Field(None, alias="ReimbursementLimit")
    RequestedTreatmentCount_: Union[str, None] = Field(
        None, alias="RequestedTreatmentCount"
    )
    RequestedTreatmentUnits_: Union[str, None] = Field(
        None, alias="RequestedTreatmentUnits"
    )


class AuthResponseReferralAuthorizationCompany(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    Name_: Union[str, None] = Field(None, alias="Name")


class AuthResponseReferralAuthorizationPlan(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    Name_: Union[str, None] = Field(None, alias="Name")


class AuthResponseReferralDiagnosis(RedoxAbstractModel):
    Code_: Union[str, None] = Field(None, alias="Code")
    Codeset_: Union[str, None] = Field(None, alias="Codeset")
    DocumentedDateTime_: Union[str, None] = Field(None, alias="DocumentedDateTime")
    Name_: Union[str, None] = Field(None, alias="Name")
    Notes_: List[str] = Field(None, alias="Notes")
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseReferralProcedure(RedoxAbstractModel):
    Authorization_: AuthResponseReferralProcedureAuthorization = Field(
        None, alias="Authorization"
    )
    Code_: Union[str, None] = Field(None, alias="Code")
    Codeset_: Union[str, None] = Field(None, alias="Codeset")
    Description_: Union[str, None] = Field(None, alias="Description")
    Modifiers_: List[str] = Field(None, alias="Modifiers")
    Notes_: List[str] = Field(None, alias="Notes")
    Quantity_: Union[str, None] = Field(None, alias="Quantity")
    Status_: Union[str, None] = Field(None, alias="Status")
    StatusReason_: Union[str, None] = Field(None, alias="StatusReason")
    Units_: Union[str, None] = Field(None, alias="Units")


class AuthResponseReferralProcedureAuthorization(RedoxAbstractModel):
    DateTime_: Union[str, None] = Field(None, alias="DateTime")
    ExpirationDateTime_: Union[str, None] = Field(None, alias="ExpirationDateTime")


class AuthResponseReferralProvider(RedoxAbstractModel):
    Address_: AuthResponseReferralProviderAddress = Field(None, alias="Address")
    ContactInfo_: Union[str, None] = Field(None, alias="ContactInfo")
    Credentials_: List[str] = Field(None, alias="Credentials")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    Location_: AuthResponseReferralProviderLocation = Field(None, alias="Location")
    PhoneNumber_: AuthResponseReferralProviderPhoneNumber = Field(
        None, alias="PhoneNumber"
    )
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseReferralProviderAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class AuthResponseReferralProviderLocation(RedoxAbstractModel):
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[
        AuthResponseReferralProviderLocationDepartmentIdentifier
    ] = Field(None, alias="DepartmentIdentifiers")
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[
        AuthResponseReferralProviderLocationFacilityIdentifier
    ] = Field(None, alias="FacilityIdentifiers")
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class AuthResponseReferralProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class AuthResponseReferralProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class AuthResponseReferralProviderPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


class AuthResponseReferralVisit(RedoxAbstractModel):
    VisitNumber_: Union[str, None] = Field(None, alias="VisitNumber")


AuthResponse.model_rebuild()
AuthResponseAuthorization.model_rebuild()
AuthResponseAuthorizationProvider.model_rebuild()
AuthResponseAuthorizationProviderLocation.model_rebuild()
AuthResponseAuthorizationService.model_rebuild()
AuthResponseMeta.model_rebuild()
AuthResponsePatient.model_rebuild()
AuthResponsePatientContact.model_rebuild()
AuthResponsePatientDemographics.model_rebuild()
AuthResponsePatientInsurance.model_rebuild()
AuthResponsePatientInsuranceCompany.model_rebuild()
AuthResponsePatientInsuranceInsured.model_rebuild()
AuthResponseReferral.model_rebuild()
AuthResponseReferralAuthorization.model_rebuild()
AuthResponseReferralProcedure.model_rebuild()
AuthResponseReferralProvider.model_rebuild()
AuthResponseReferralProviderLocation.model_rebuild()
