# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #
from __future__ import annotations

from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class New(EventTypeAbstractModel):
    Meta: NewMeta = Field(..., alias="Meta")
    Patient: NewPatient = Field(..., alias="Patient")
    Referral: NewReferral = Field(None, alias="Referral")
    Visit: NewVisit = Field(None, alias="Visit")


class NewMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list[NewMetaDestination] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list[NewMetaLog] = Field(None, alias="Logs")
    Source: NewMetaSource = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class NewMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class NewMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class NewMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class NewPatient(RedoxAbstractModel):
    Contacts: list[NewPatientContact] = Field(None, alias="Contacts")
    Demographics: NewPatientDemographics = Field(None, alias="Demographics")
    Guarantor: NewPatientGuarantor = Field(None, alias="Guarantor")
    Identifiers: list[NewPatientIdentifier] = Field(..., alias="Identifiers")
    Insurances: list[NewPatientInsurance] = Field(None, alias="Insurances")
    Notes: list[str] = Field(None, alias="Notes")


class NewPatientContact(RedoxAbstractModel):
    Address: NewPatientContactAddress = Field(None, alias="Address")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: NewPatientContactPhoneNumber = Field(None, alias="PhoneNumber")
    RelationToPatient: str | None = Field(None, alias="RelationToPatient")
    Roles: list[str] = Field(None, alias="Roles")


class NewPatientContactAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewPatientContactPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class NewPatientDemographics(RedoxAbstractModel):
    Address: NewPatientDemographicsAddress = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: NewPatientDemographicsPhoneNumber = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class NewPatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewPatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class NewPatientGuarantor(RedoxAbstractModel):
    Address: NewPatientGuarantorAddress = Field(None, alias="Address")
    DOB: str | None = Field(None, alias="DOB")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    Employer: NewPatientGuarantorEmployer = Field(None, alias="Employer")
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    Number: str | None = Field(None, alias="Number")
    PhoneNumber: NewPatientGuarantorPhoneNumber = Field(None, alias="PhoneNumber")
    RelationToPatient: str | None = Field(None, alias="RelationToPatient")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")
    Spouse: NewPatientGuarantorSpouse = Field(None, alias="Spouse")
    Type: str | None = Field(None, alias="Type")


class NewPatientGuarantorAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewPatientGuarantorEmployer(RedoxAbstractModel):
    Address: NewPatientGuarantorEmployerAddress = Field(None, alias="Address")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class NewPatientGuarantorEmployerAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewPatientGuarantorPhoneNumber(RedoxAbstractModel):
    Business: str | None = Field(None, alias="Business")
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")


class NewPatientGuarantorSpouse(RedoxAbstractModel):
    FirstName: str | None = Field(None, alias="FirstName")
    LastName: str | None = Field(None, alias="LastName")


class NewPatientIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str = Field(..., alias="IDType")


class NewPatientInsurance(RedoxAbstractModel):
    AgreementType: str | None = Field(None, alias="AgreementType")
    Company: NewPatientInsuranceCompany = Field(None, alias="Company")
    CoverageType: str | None = Field(None, alias="CoverageType")
    EffectiveDate: str | None = Field(None, alias="EffectiveDate")
    ExpirationDate: str | None = Field(None, alias="ExpirationDate")
    GroupName: str | None = Field(None, alias="GroupName")
    GroupNumber: str | None = Field(None, alias="GroupNumber")
    Insured: NewPatientInsuranceInsured = Field(None, alias="Insured")
    MemberNumber: str | None = Field(None, alias="MemberNumber")
    Plan: NewPatientInsurancePlan = Field(None, alias="Plan")
    PolicyNumber: str | None = Field(None, alias="PolicyNumber")
    Priority: str | None = Field(None, alias="Priority")


class NewPatientInsuranceCompany(RedoxAbstractModel):
    Address: NewPatientInsuranceCompanyAddress = Field(None, alias="Address")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")
    PhoneNumber: str | None = Field(None, alias="PhoneNumber")


class NewPatientInsuranceCompanyAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewPatientInsuranceInsured(RedoxAbstractModel):
    Address: NewPatientInsuranceInsuredAddress = Field(None, alias="Address")
    DOB: str | None = Field(None, alias="DOB")
    FirstName: str | None = Field(None, alias="FirstName")
    Identifiers: list[NewPatientInsuranceInsuredIdentifier] = Field(None, alias="Identifiers")
    LastName: str | None = Field(None, alias="LastName")
    MiddleName: str | None = Field(None, alias="MiddleName")
    Relationship: str | None = Field(None, alias="Relationship")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class NewPatientInsuranceInsuredAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewPatientInsuranceInsuredIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewPatientInsurancePlan(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class NewReferral(RedoxAbstractModel):
    AlternateID: str | None = Field(None, alias="AlternateID")
    Authorization: NewReferralAuthorization = Field(None, alias="Authorization")
    Category: str | None = Field(None, alias="Category")
    DateTime: str | None = Field(None, alias="DateTime")
    DepartmentSpecialty: str | None = Field(None, alias="DepartmentSpecialty")
    Diagnoses: list[NewReferralDiagnosis] = Field(None, alias="Diagnoses")
    ExpirationDateTime: str | None = Field(None, alias="ExpirationDateTime")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Notes: list[str] = Field(None, alias="Notes")
    Priority: str | None = Field(None, alias="Priority")
    Procedures: list[NewReferralProcedure] = Field(None, alias="Procedures")
    ProcessDateTime: str | None = Field(None, alias="ProcessDateTime")
    ProviderSpecialty: str | None = Field(None, alias="ProviderSpecialty")
    Providers: list[NewReferralProvider] = Field(None, alias="Providers")
    Reason: str | None = Field(None, alias="Reason")
    Status: str | None = Field(None, alias="Status")
    Type: str | None = Field(None, alias="Type")
    Visit: NewReferralVisit = Field(None, alias="Visit")


class NewReferralAuthorization(RedoxAbstractModel):
    AuthorizedTreatmentCount: str | None = Field(None, alias="AuthorizedTreatmentCount")
    Company: NewReferralAuthorizationCompany = Field(None, alias="Company")
    DateTime: str | None = Field(None, alias="DateTime")
    ExpirationDateTime: str | None = Field(None, alias="ExpirationDateTime")
    Notes: list[str] = Field(None, alias="Notes")
    Number: str | None = Field(None, alias="Number")
    Plan: NewReferralAuthorizationPlan = Field(None, alias="Plan")
    ReimbursementLimit: str | None = Field(None, alias="ReimbursementLimit")
    RequestedTreatmentCount: str | None = Field(None, alias="RequestedTreatmentCount")
    RequestedTreatmentUnits: str | None = Field(None, alias="RequestedTreatmentUnits")


class NewReferralAuthorizationCompany(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")


class NewReferralAuthorizationPlan(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    Name: str | None = Field(None, alias="Name")


class NewReferralDiagnosis(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    DocumentedDateTime: str | None = Field(None, alias="DocumentedDateTime")
    Name: str | None = Field(None, alias="Name")
    Notes: list[str] = Field(None, alias="Notes")
    Type: str | None = Field(None, alias="Type")


class NewReferralProcedure(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    Modifiers: list[str] = Field(None, alias="Modifiers")
    Notes: list[str] = Field(None, alias="Notes")
    Quantity: str | None = Field(None, alias="Quantity")
    Units: str | None = Field(None, alias="Units")


class NewReferralProvider(RedoxAbstractModel):
    Address: NewReferralProviderAddress = Field(None, alias="Address")
    ContactInfo: str | None = Field(None, alias="ContactInfo")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: NewReferralProviderLocation = Field(None, alias="Location")
    PhoneNumber: NewReferralProviderPhoneNumber = Field(None, alias="PhoneNumber")
    Type: str | None = Field(None, alias="Type")


class NewReferralProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NewReferralProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list[NewReferralProviderLocationDepartmentIdentifier] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list[NewReferralProviderLocationFacilityIdentifier] = Field(None, alias="FacilityIdentifiers")
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NewReferralProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewReferralProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NewReferralProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class NewReferralVisit(RedoxAbstractModel):
    VisitNumber: str | None = Field(None, alias="VisitNumber")


class NewVisit(RedoxAbstractModel):
    VisitNumber: str | None = Field(None, alias="VisitNumber")


New.model_rebuild()
NewMeta.model_rebuild()
NewPatient.model_rebuild()
NewPatientContact.model_rebuild()
NewPatientDemographics.model_rebuild()
NewPatientGuarantor.model_rebuild()
NewPatientGuarantorEmployer.model_rebuild()
NewPatientInsurance.model_rebuild()
NewPatientInsuranceCompany.model_rebuild()
NewPatientInsuranceInsured.model_rebuild()
NewReferral.model_rebuild()
NewReferralAuthorization.model_rebuild()
NewReferralProvider.model_rebuild()
NewReferralProviderLocation.model_rebuild()
