# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class NormalizationQuery(EventTypeAbstractModel):
    Entries: list["NormalizationQueryEntry"] = Field(..., alias="Entries")
    Meta: "NormalizationQueryMeta" = Field(..., alias="Meta")


class NormalizationQueryEntry(RedoxAbstractModel):
    Category: str = Field(..., alias="Category")
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    EntryID: str | None = Field(None, alias="EntryID")


class NormalizationQueryMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["NormalizationQueryMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["NormalizationQueryMetaLog"] = Field(None, alias="Logs")
    Source: "NormalizationQueryMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class NormalizationQueryMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class NormalizationQueryMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class NormalizationQueryMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


NormalizationQuery.model_rebuild()
NormalizationQueryMeta.model_rebuild()
