# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class PatientQuery(EventTypeAbstractModel):
    Location: "PatientQueryLocation" = Field(None, alias="Location")
    Meta: "PatientQueryMeta" = Field(..., alias="Meta")
    Patient: "PatientQueryPatient" = Field(..., alias="Patient")


class PatientQueryLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")


class PatientQueryMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["PatientQueryMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["PatientQueryMetaLog"] = Field(None, alias="Logs")
    Source: "PatientQueryMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class PatientQueryMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class PatientQueryMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class PatientQueryMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class PatientQueryPatient(RedoxAbstractModel):
    Identifiers: list["PatientQueryPatientIdentifier"] = Field(..., alias="Identifiers")


class PatientQueryPatientIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str = Field(..., alias="IDType")


PatientQuery.model_rebuild()
PatientQueryMeta.model_rebuild()
PatientQueryPatient.model_rebuild()
