# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class Cancel(EventTypeAbstractModel):
    Meta: "CancelMeta" = Field(..., alias="Meta")
    Patient: "CancelPatient" = Field(..., alias="Patient")
    Procedures: list["CancelProcedure"] = Field(..., alias="Procedures")
    SurgeryStaff: list["CancelSurgeryStaff"] = Field(None, alias="SurgeryStaff")
    SurgicalCase: "CancelSurgicalCase" = Field(None, alias="SurgicalCase")
    SurgicalInfo: list["CancelSurgicalInfo"] = Field(None, alias="SurgicalInfo")
    Visit: "CancelVisit" = Field(..., alias="Visit")


class CancelMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["CancelMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["CancelMetaLog"] = Field(None, alias="Logs")
    Source: "CancelMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class CancelMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class CancelMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class CancelMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class CancelPatient(RedoxAbstractModel):
    Demographics: "CancelPatientDemographics" = Field(None, alias="Demographics")
    Identifiers: list["CancelPatientIdentifier"] = Field(..., alias="Identifiers")
    Notes: list[str] = Field(None, alias="Notes")


class CancelPatientDemographics(RedoxAbstractModel):
    Address: "CancelPatientDemographicsAddress" = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "CancelPatientDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class CancelPatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class CancelPatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class CancelPatientIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str = Field(..., alias="IDType")


class CancelProcedure(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    DateTime: str | None = Field(None, alias="DateTime")
    Description: str | None = Field(None, alias="Description")
    Duration: float = Field(..., alias="Duration")
    ProcedureInfo: list["CancelProcedureProcedureInfo"] = Field(None, alias="ProcedureInfo")


class CancelProcedureProcedureInfo(RedoxAbstractModel):
    Description: str | None = Field(None, alias="Description")
    Value: str | None = Field(None, alias="Value")


class CancelSurgeryStaff(RedoxAbstractModel):
    Address: "CancelSurgeryStaffAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    Duration: float | None = Field(None, alias="Duration")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "CancelSurgeryStaffLocation" = Field(None, alias="Location")
    PhoneNumber: "CancelSurgeryStaffPhoneNumber" = Field(None, alias="PhoneNumber")
    Role: "CancelSurgeryStaffRole" = Field(None, alias="Role")
    StartDateTime: str | None = Field(None, alias="StartDateTime")


class CancelSurgeryStaffAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class CancelSurgeryStaffLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["CancelSurgeryStaffLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["CancelSurgeryStaffLocationFacilityIdentifier"] = Field(None, alias="FacilityIdentifiers")
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class CancelSurgeryStaffLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class CancelSurgeryStaffLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class CancelSurgeryStaffPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class CancelSurgeryStaffRole(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


class CancelSurgicalCase(RedoxAbstractModel):
    Number: str | None = Field(None, alias="Number")
    Status: str | None = Field(None, alias="Status")


class CancelSurgicalInfo(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    Value: str | None = Field(None, alias="Value")


class CancelVisit(RedoxAbstractModel):
    AccountNumber: str | None = Field(None, alias="AccountNumber")
    AttendingProvider: "CancelVisitAttendingProvider" = Field(None, alias="AttendingProvider")
    CancelReason: str | None = Field(None, alias="CancelReason")
    Diagnoses: list["CancelVisitDiagnosis"] = Field(None, alias="Diagnoses")
    Duration: float | None = Field(None, alias="Duration")
    Equipment: list["CancelVisitEquipment"] = Field(None, alias="Equipment")
    Location: "CancelVisitLocation" = Field(..., alias="Location")
    Notes: list[str] = Field(None, alias="Notes")
    PatientClass: str | None = Field(None, alias="PatientClass")
    Status: str | None = Field(None, alias="Status")
    VisitDateTime: str | None = Field(None, alias="VisitDateTime")
    VisitNumber: str = Field(..., alias="VisitNumber")


class CancelVisitAttendingProvider(RedoxAbstractModel):
    Address: "CancelVisitAttendingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "CancelVisitAttendingProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "CancelVisitAttendingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class CancelVisitAttendingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class CancelVisitAttendingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["CancelVisitAttendingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["CancelVisitAttendingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class CancelVisitAttendingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class CancelVisitAttendingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class CancelVisitAttendingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class CancelVisitDiagnosis(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    DocumentedDateTime: str | None = Field(None, alias="DocumentedDateTime")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class CancelVisitEquipment(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    Duration: float | None = Field(None, alias="Duration")
    StartDateTime: str | None = Field(None, alias="StartDateTime")


class CancelVisitLocation(RedoxAbstractModel):
    Bed: str | None = Field(None, alias="Bed")
    Department: str = Field(..., alias="Department")
    DepartmentIdentifiers: list["CancelVisitLocationDepartmentIdentifier"] = Field(None, alias="DepartmentIdentifiers")
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["CancelVisitLocationFacilityIdentifier"] = Field(None, alias="FacilityIdentifiers")
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class CancelVisitLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class CancelVisitLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


Cancel.model_rebuild()
CancelMeta.model_rebuild()
CancelPatient.model_rebuild()
CancelPatientDemographics.model_rebuild()
CancelProcedure.model_rebuild()
CancelSurgeryStaff.model_rebuild()
CancelSurgeryStaffLocation.model_rebuild()
CancelVisit.model_rebuild()
CancelVisitAttendingProvider.model_rebuild()
CancelVisitAttendingProviderLocation.model_rebuild()
CancelVisitLocation.model_rebuild()
