# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class PatientMerge(EventTypeAbstractModel):
    Meta: "PatientMergeMeta" = Field(..., alias="Meta")
    Patient: "PatientMergePatient" = Field(..., alias="Patient")


class PatientMergeMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["PatientMergeMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["PatientMergeMetaLog"] = Field(None, alias="Logs")
    Source: "PatientMergeMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class PatientMergeMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class PatientMergeMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class PatientMergeMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class PatientMergePatient(RedoxAbstractModel):
    Demographics: "PatientMergePatientDemographics" = Field(None, alias="Demographics")
    Identifiers: list["PatientMergePatientIdentifier"] = Field(..., alias="Identifiers")
    Notes: list[str] = Field(None, alias="Notes")
    PreviousIdentifiers: list["PatientMergePatientPreviousIdentifier"] = Field(..., alias="PreviousIdentifiers")


class PatientMergePatientDemographics(RedoxAbstractModel):
    Address: "PatientMergePatientDemographicsAddress" = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "PatientMergePatientDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class PatientMergePatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class PatientMergePatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class PatientMergePatientIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str = Field(..., alias="IDType")


class PatientMergePatientPreviousIdentifier(RedoxAbstractModel):
    ID: str = Field(..., alias="ID")
    IDType: str = Field(..., alias="IDType")


PatientMerge.model_rebuild()
PatientMergeMeta.model_rebuild()
PatientMergePatient.model_rebuild()
PatientMergePatientDemographics.model_rebuild()
