# -*- coding: utf-8 -*-
# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #

from __future__ import annotations

from typing import List

from pydantic import Field

from redox import claim
from ..abstract_base import GenericEventTypeAbstractModel
from . import types as generic


class _Claim(GenericEventTypeAbstractModel):
    _redox_module = claim


class Payment(_Claim):
    Meta_: generic.Meta = Field(..., alias="Meta")
    Payee_: generic.Payee = Field(None, alias="Payee")
    Payer_: generic.Payer = Field(None, alias="Payer")
    Payments_: List[generic.Payment] = Field(..., alias="Payments")
    Transaction_: generic.Transaction = Field(None, alias="Transaction")


class PaymentBatch(_Claim):
    Meta_: generic.Meta = Field(..., alias="Meta")
    Transactions_: List[generic.Transaction] = Field(None, alias="Transactions")


class Submission(_Claim):
    BillingProvider_: generic.BillingProvider = Field(None, alias="BillingProvider")
    Claims_: List[generic.Claim] = Field(None, alias="Claims")
    Meta_: generic.Meta = Field(..., alias="Meta")
    Patient_: generic.Patient = Field(None, alias="Patient")
    Subscriber_: generic.Subscriber = Field(None, alias="Subscriber")
    Transaction_: generic.Transaction = Field(None, alias="Transaction")


class SubmissionBatch(_Claim):
    Meta_: generic.Meta = Field(..., alias="Meta")
    Transactions_: List[generic.Transaction] = Field(None, alias="Transactions")
