# -*- coding: utf-8 -*-
# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #

from __future__ import annotations

from typing import List

from pydantic import Field

from redox import flowsheet
from ..abstract_base import GenericEventTypeAbstractModel
from . import types as generic


class _Flowsheet(GenericEventTypeAbstractModel):
    _redox_module = flowsheet


class New(_Flowsheet):
    Meta_: generic.Meta = Field(..., alias="Meta")
    Observations_: List[generic.Observation] = Field(..., alias="Observations")
    Patient_: generic.Patient = Field(..., alias="Patient")
    Visit_: generic.Visit = Field(None, alias="Visit")
