# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #
from __future__ import annotations

from pydantic import Field

from redox import notes
from redox.abstract_base import GenericEventTypeAbstractModel

from . import types as generic


class _Notes(GenericEventTypeAbstractModel):
    _redox_module = notes


class Delete(_Notes):
    Meta: generic._Meta = Field(..., alias="Meta")
    Note: generic._Note = Field(..., alias="Note")
    Orders: list[generic._Order] = Field(None, alias="Orders")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")


class New(_Notes):
    Meta: generic._Meta = Field(..., alias="Meta")
    Note: generic._Note = Field(..., alias="Note")
    Orders: list[generic._Order] = Field(None, alias="Orders")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")


class Query(_Notes):
    DocumentIDs: list[str] = Field(None, alias="DocumentIDs")
    DocumentTypes: list[str] = Field(None, alias="DocumentTypes")
    Meta: generic._Meta = Field(..., alias="Meta")
    Patients: list[generic._Patient] = Field(None, alias="Patients")
    VisitNumbers: list[str] = Field(None, alias="VisitNumbers")


class QueryResponse(_Notes):
    Meta: generic._Meta = Field(..., alias="Meta")
    Notes: list[generic._Note] = Field(None, alias="Notes")


class Replace(_Notes):
    Meta: generic._Meta = Field(..., alias="Meta")
    Note: generic._Note = Field(..., alias="Note")
    Orders: list[generic._Order] = Field(None, alias="Orders")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")
