# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #
from __future__ import annotations

from pydantic import Field

from redox import organization
from redox.abstract_base import GenericEventTypeAbstractModel

from . import types as generic


class _Organization(GenericEventTypeAbstractModel):
    _redox_module = organization


class New(_Organization):
    Directory: str = Field(..., alias="Directory")
    Meta: generic._Meta = Field(..., alias="Meta")
    Organizations: list[generic._Organization] = Field(..., alias="Organizations")


class Query(_Organization):
    Active: bool | None = Field(None, alias="Active")
    Directory: str = Field(..., alias="Directory")
    Identifier: generic._Identifier = Field(None, alias="Identifier")
    Index: str | None = Field(None, alias="Index")
    LastUpdated: str | None = Field(None, alias="LastUpdated")
    Limit: str | None = Field(None, alias="Limit")
    Meta: generic._Meta = Field(..., alias="Meta")
    NameSearch: generic._NameSearch = Field(None, alias="NameSearch")
    RadiusSearch: generic._RadiusSearch = Field(None, alias="RadiusSearch")
    State: str | None = Field(None, alias="State")


class QueryResponse(_Organization):
    Directory: str = Field(..., alias="Directory")
    Meta: generic._Meta = Field(..., alias="Meta")
    Organizations: list[generic._Organization] = Field(..., alias="Organizations")
    Paging: generic._Paging = Field(None, alias="Paging")


class Update(_Organization):
    Action: str = Field(..., alias="Action")
    Directory: str = Field(..., alias="Directory")
    Meta: generic._Meta = Field(..., alias="Meta")
    Organizations: list[generic._Organization] = Field(..., alias="Organizations")
