# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox import patientadmin
from redox.abstract_base import GenericEventTypeAbstractModel

from . import types as generic


class _PatientAdmin(GenericEventTypeAbstractModel):
    _redox_module = patientadmin


class Arrival(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")


class Cancel(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")


class CensusQuery(_PatientAdmin):
    Departments: list[str] = Field(None, alias="Departments")
    Facilities: list[str] = Field(None, alias="Facilities")
    Meta: generic._Meta = Field(..., alias="Meta")
    PatientClasses: list[str] = Field(None, alias="PatientClasses")


class CensusQueryResponse(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patients: list[generic._Patient] = Field(None, alias="Patients")


class Discharge(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")


class NewPatient(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")


class PatientMerge(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")


class PatientUpdate(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")


class PreAdmit(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")


class Registration(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")


class Transfer(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")


class VisitMerge(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(..., alias="Visit")


class VisitQuery(_PatientAdmin):
    Departments: list[str] = Field(None, alias="Departments")
    Facilities: list[str] = Field(None, alias="Facilities")
    Meta: generic._Meta = Field(..., alias="Meta")
    PatientClasses: list[str] = Field(None, alias="PatientClasses")
    Patients: list[generic._Patient] = Field(None, alias="Patients")
    VisitNumbers: list[str] = Field(None, alias="VisitNumbers")
    VisitStartDateTime: str | None = Field(None, alias="VisitStartDateTime")
    VisitStatuses: list[str] = Field(None, alias="VisitStatuses")


class VisitQueryResponse(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patients: list[generic._Patient] = Field(None, alias="Patients")


class VisitUpdate(_PatientAdmin):
    Meta: generic._Meta = Field(..., alias="Meta")
    Patient: generic._Patient = Field(..., alias="Patient")
    Visit: generic._Visit = Field(None, alias="Visit")
