# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class AvailableSlots(EventTypeAbstractModel):
    EndDateTime: str | None = Field(None, alias="EndDateTime")
    Meta: "AvailableSlotsMeta" = Field(..., alias="Meta")
    Patient: "AvailableSlotsPatient" = Field(None, alias="Patient")
    StartDateTime: str = Field(..., alias="StartDateTime")
    Visit: "AvailableSlotsVisit" = Field(None, alias="Visit")


class AvailableSlotsMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["AvailableSlotsMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["AvailableSlotsMetaLog"] = Field(None, alias="Logs")
    Source: "AvailableSlotsMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class AvailableSlotsMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class AvailableSlotsMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class AvailableSlotsMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class AvailableSlotsPatient(RedoxAbstractModel):
    Demographics: "AvailableSlotsPatientDemographics" = Field(None, alias="Demographics")
    Diagnoses: list["AvailableSlotsPatientDiagnosis"] = Field(None, alias="Diagnoses")
    Identifiers: list["AvailableSlotsPatientIdentifier"] = Field(None, alias="Identifiers")
    Notes: list[str] = Field(None, alias="Notes")


class AvailableSlotsPatientDemographics(RedoxAbstractModel):
    Address: "AvailableSlotsPatientDemographicsAddress" = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "AvailableSlotsPatientDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class AvailableSlotsPatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class AvailableSlotsPatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class AvailableSlotsPatientDiagnosis(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    DocumentedDateTime: str | None = Field(None, alias="DocumentedDateTime")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class AvailableSlotsPatientIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class AvailableSlotsVisit(RedoxAbstractModel):
    AttendingProviders: list["AvailableSlotsVisitAttendingProvider"] = Field(None, alias="AttendingProviders")
    Locations: list["AvailableSlotsVisitLocation"] = Field(None, alias="Locations")
    Reasons: list[str] = Field(None, alias="Reasons")
    VisitPreference: list["AvailableSlotsVisitVisitPreference"] = Field(None, alias="VisitPreference")
    VisitType: list["AvailableSlotsVisitVisitType"] = Field(None, alias="VisitType")


class AvailableSlotsVisitAttendingProvider(RedoxAbstractModel):
    Address: "AvailableSlotsVisitAttendingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "AvailableSlotsVisitAttendingProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "AvailableSlotsVisitAttendingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class AvailableSlotsVisitAttendingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class AvailableSlotsVisitAttendingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["AvailableSlotsVisitAttendingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["AvailableSlotsVisitAttendingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class AvailableSlotsVisitAttendingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class AvailableSlotsVisitAttendingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class AvailableSlotsVisitAttendingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class AvailableSlotsVisitLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    Facility: str | None = Field(None, alias="Facility")
    ID: str | None = Field(None, alias="ID")
    Room: str | None = Field(None, alias="Room")
    SpecialtyDepartment: "AvailableSlotsVisitLocationSpecialtyDepartment" = Field(None, alias="SpecialtyDepartment")
    Type: str | None = Field(None, alias="Type")


class AvailableSlotsVisitLocationSpecialtyDepartment(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


class AvailableSlotsVisitVisitPreference(RedoxAbstractModel):
    Day: list[str] = Field(None, alias="Day")
    Duration: str | None = Field(None, alias="Duration")
    DurationUnit: str | None = Field(None, alias="DurationUnit")
    Time: list[str] = Field(None, alias="Time")


class AvailableSlotsVisitVisitType(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


AvailableSlots.model_rebuild()
AvailableSlotsMeta.model_rebuild()
AvailableSlotsPatient.model_rebuild()
AvailableSlotsPatientDemographics.model_rebuild()
AvailableSlotsVisit.model_rebuild()
AvailableSlotsVisitAttendingProvider.model_rebuild()
AvailableSlotsVisitAttendingProviderLocation.model_rebuild()
AvailableSlotsVisitLocation.model_rebuild()
