# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #


from pydantic import Field

from redox.abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class NoShow(EventTypeAbstractModel):
    AppointmentInfo: list["NoShowAppointmentInfo"] = Field(None, alias="AppointmentInfo")
    Meta: "NoShowMeta" = Field(..., alias="Meta")
    Patient: "NoShowPatient" = Field(None, alias="Patient")
    Visit: "NoShowVisit" = Field(..., alias="Visit")


class NoShowAppointmentInfo(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    Value: str | None = Field(None, alias="Value")


class NoShowMeta(RedoxAbstractModel):
    DataModel: str = Field(..., alias="DataModel")
    Destinations: list["NoShowMetaDestination"] = Field(None, alias="Destinations")
    EventDateTime: str | None = Field(None, alias="EventDateTime")
    EventType: str = Field(..., alias="EventType")
    FacilityCode: str | None = Field(None, alias="FacilityCode")
    Logs: list["NoShowMetaLog"] = Field(None, alias="Logs")
    Source: "NoShowMetaSource" = Field(None, alias="Source")
    Test: bool | None = Field(None, alias="Test")


class NoShowMetaDestination(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class NoShowMetaLog(RedoxAbstractModel):
    AttemptID: str | None = Field(None, alias="AttemptID")
    ID: str | None = Field(None, alias="ID")


class NoShowMetaSource(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    Name: str | None = Field(None, alias="Name")


class NoShowPatient(RedoxAbstractModel):
    Demographics: "NoShowPatientDemographics" = Field(None, alias="Demographics")
    Identifiers: list["NoShowPatientIdentifier"] = Field(None, alias="Identifiers")
    Notes: list[str] = Field(None, alias="Notes")


class NoShowPatientDemographics(RedoxAbstractModel):
    Address: "NoShowPatientDemographicsAddress" = Field(None, alias="Address")
    Citizenship: list[str] = Field(None, alias="Citizenship")
    DOB: str | None = Field(None, alias="DOB")
    DeathDateTime: str | None = Field(None, alias="DeathDateTime")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    IsDeceased: bool | None = Field(None, alias="IsDeceased")
    IsHispanic: bool | None = Field(None, alias="IsHispanic")
    Language: str | None = Field(None, alias="Language")
    LastName: str | None = Field(None, alias="LastName")
    MaritalStatus: str | None = Field(None, alias="MaritalStatus")
    MiddleName: str | None = Field(None, alias="MiddleName")
    PhoneNumber: "NoShowPatientDemographicsPhoneNumber" = Field(None, alias="PhoneNumber")
    Race: str | None = Field(None, alias="Race")
    Religion: str | None = Field(None, alias="Religion")
    SSN: str | None = Field(None, alias="SSN")
    Sex: str | None = Field(None, alias="Sex")


class NoShowPatientDemographicsAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NoShowPatientDemographicsPhoneNumber(RedoxAbstractModel):
    Home: str | None = Field(None, alias="Home")
    Mobile: str | None = Field(None, alias="Mobile")
    Office: str | None = Field(None, alias="Office")


class NoShowPatientIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisit(RedoxAbstractModel):
    AccountNumber: str | None = Field(None, alias="AccountNumber")
    AdditionalStaff: list["NoShowVisitAdditionalStaff"] = Field(None, alias="AdditionalStaff")
    AttendingProvider: "NoShowVisitAttendingProvider" = Field(None, alias="AttendingProvider")
    ConsultingProvider: "NoShowVisitConsultingProvider" = Field(None, alias="ConsultingProvider")
    Diagnoses: list["NoShowVisitDiagnosis"] = Field(None, alias="Diagnoses")
    Duration: float | None = Field(None, alias="Duration")
    Equipment: list["NoShowVisitEquipment"] = Field(None, alias="Equipment")
    Instructions: list[str] = Field(None, alias="Instructions")
    Location: "NoShowVisitLocation" = Field(..., alias="Location")
    NoShowReason: str | None = Field(None, alias="NoShowReason")
    PatientClass: str | None = Field(None, alias="PatientClass")
    Reason: str | None = Field(None, alias="Reason")
    ReferringProvider: "NoShowVisitReferringProvider" = Field(None, alias="ReferringProvider")
    Status: str | None = Field(None, alias="Status")
    Type: str | None = Field(None, alias="Type")
    VisitDateTime: str = Field(..., alias="VisitDateTime")
    VisitNumber: str = Field(..., alias="VisitNumber")
    VisitProvider: "NoShowVisitVisitProvider" = Field(None, alias="VisitProvider")


class NoShowVisitAdditionalStaff(RedoxAbstractModel):
    Address: "NoShowVisitAdditionalStaffAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    Duration: float | None = Field(None, alias="Duration")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "NoShowVisitAdditionalStaffLocation" = Field(None, alias="Location")
    PhoneNumber: "NoShowVisitAdditionalStaffPhoneNumber" = Field(None, alias="PhoneNumber")
    Role: "NoShowVisitAdditionalStaffRole" = Field(None, alias="Role")
    StartDateTime: str | None = Field(None, alias="StartDateTime")


class NoShowVisitAdditionalStaffAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NoShowVisitAdditionalStaffLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NoShowVisitAdditionalStaffLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NoShowVisitAdditionalStaffLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NoShowVisitAdditionalStaffLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitAdditionalStaffLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitAdditionalStaffPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class NoShowVisitAdditionalStaffRole(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")


class NoShowVisitAttendingProvider(RedoxAbstractModel):
    Address: "NoShowVisitAttendingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "NoShowVisitAttendingProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "NoShowVisitAttendingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class NoShowVisitAttendingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NoShowVisitAttendingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NoShowVisitAttendingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NoShowVisitAttendingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NoShowVisitAttendingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitAttendingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitAttendingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class NoShowVisitConsultingProvider(RedoxAbstractModel):
    Address: "NoShowVisitConsultingProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "NoShowVisitConsultingProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "NoShowVisitConsultingProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class NoShowVisitConsultingProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NoShowVisitConsultingProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NoShowVisitConsultingProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NoShowVisitConsultingProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NoShowVisitConsultingProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitConsultingProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitConsultingProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class NoShowVisitDiagnosis(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    DocumentedDateTime: str | None = Field(None, alias="DocumentedDateTime")
    Name: str | None = Field(None, alias="Name")
    Type: str | None = Field(None, alias="Type")


class NoShowVisitEquipment(RedoxAbstractModel):
    Code: str | None = Field(None, alias="Code")
    Codeset: str | None = Field(None, alias="Codeset")
    Description: str | None = Field(None, alias="Description")
    Duration: float | None = Field(None, alias="Duration")
    StartDateTime: str | None = Field(None, alias="StartDateTime")


class NoShowVisitLocation(RedoxAbstractModel):
    Department: str = Field(..., alias="Department")
    DepartmentIdentifiers: list["NoShowVisitLocationDepartmentIdentifier"] = Field(None, alias="DepartmentIdentifiers")
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NoShowVisitLocationFacilityIdentifier"] = Field(None, alias="FacilityIdentifiers")
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NoShowVisitLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitReferringProvider(RedoxAbstractModel):
    Address: "NoShowVisitReferringProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "NoShowVisitReferringProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "NoShowVisitReferringProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class NoShowVisitReferringProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NoShowVisitReferringProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NoShowVisitReferringProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NoShowVisitReferringProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NoShowVisitReferringProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitReferringProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitReferringProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


class NoShowVisitVisitProvider(RedoxAbstractModel):
    Address: "NoShowVisitVisitProviderAddress" = Field(None, alias="Address")
    Credentials: list[str] = Field(None, alias="Credentials")
    EmailAddresses: list[str] = Field(None, alias="EmailAddresses")
    FirstName: str | None = Field(None, alias="FirstName")
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")
    LastName: str | None = Field(None, alias="LastName")
    Location: "NoShowVisitVisitProviderLocation" = Field(None, alias="Location")
    PhoneNumber: "NoShowVisitVisitProviderPhoneNumber" = Field(None, alias="PhoneNumber")


class NoShowVisitVisitProviderAddress(RedoxAbstractModel):
    City: str | None = Field(None, alias="City")
    Country: str | None = Field(None, alias="Country")
    County: str | None = Field(None, alias="County")
    State: str | None = Field(None, alias="State")
    StreetAddress: str | None = Field(None, alias="StreetAddress")
    ZIP: str | None = Field(None, alias="ZIP")


class NoShowVisitVisitProviderLocation(RedoxAbstractModel):
    Department: str | None = Field(None, alias="Department")
    DepartmentIdentifiers: list["NoShowVisitVisitProviderLocationDepartmentIdentifier"] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility: str | None = Field(None, alias="Facility")
    FacilityIdentifiers: list["NoShowVisitVisitProviderLocationFacilityIdentifier"] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room: str | None = Field(None, alias="Room")
    Type: str | None = Field(None, alias="Type")


class NoShowVisitVisitProviderLocationDepartmentIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitVisitProviderLocationFacilityIdentifier(RedoxAbstractModel):
    ID: str | None = Field(None, alias="ID")
    IDType: str | None = Field(None, alias="IDType")


class NoShowVisitVisitProviderPhoneNumber(RedoxAbstractModel):
    Office: str | None = Field(None, alias="Office")


NoShow.model_rebuild()
NoShowMeta.model_rebuild()
NoShowPatient.model_rebuild()
NoShowPatientDemographics.model_rebuild()
NoShowVisit.model_rebuild()
NoShowVisitAdditionalStaff.model_rebuild()
NoShowVisitAdditionalStaffLocation.model_rebuild()
NoShowVisitAttendingProvider.model_rebuild()
NoShowVisitAttendingProviderLocation.model_rebuild()
NoShowVisitConsultingProvider.model_rebuild()
NoShowVisitConsultingProviderLocation.model_rebuild()
NoShowVisitLocation.model_rebuild()
NoShowVisitReferringProvider.model_rebuild()
NoShowVisitReferringProviderLocation.model_rebuild()
NoShowVisitVisitProvider.model_rebuild()
NoShowVisitVisitProviderLocation.model_rebuild()
