# -*- coding: utf-8 -*-
# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #

from __future__ import annotations

from typing import List, Union

from pydantic import Field

from ..abstract_base import EventTypeAbstractModel, RedoxAbstractModel


class PushSlots(EventTypeAbstractModel):
    Meta_: PushSlotsMeta = Field(..., alias="Meta")
    Slots_: List[PushSlotsSlot] = Field(..., alias="Slots")


class PushSlotsMeta(RedoxAbstractModel):
    BatchID_: Union[str, None] = Field(None, alias="BatchID")
    CurrentBatch_: Union[str, None] = Field(None, alias="CurrentBatch")
    DataModel_: str = Field(..., alias="DataModel")
    Destinations_: List[PushSlotsMetaDestination] = Field(None, alias="Destinations")
    EventDateTime_: Union[str, None] = Field(None, alias="EventDateTime")
    EventType_: str = Field(..., alias="EventType")
    FacilityCode_: Union[str, None] = Field(None, alias="FacilityCode")
    Logs_: List[PushSlotsMetaLog] = Field(None, alias="Logs")
    Message_: PushSlotsMetaMessage = Field(None, alias="Message")
    Source_: PushSlotsMetaSource = Field(None, alias="Source")
    Test_: Union[bool, None] = Field(None, alias="Test")
    TotalBatches_: Union[str, None] = Field(None, alias="TotalBatches")
    Transmission_: PushSlotsMetaTransmission = Field(None, alias="Transmission")


class PushSlotsMetaDestination(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    Name_: Union[str, None] = Field(None, alias="Name")


class PushSlotsMetaLog(RedoxAbstractModel):
    AttemptID_: Union[str, None] = Field(None, alias="AttemptID")
    ID_: Union[str, None] = Field(None, alias="ID")


class PushSlotsMetaMessage(RedoxAbstractModel):
    ID_: Union[float, None] = Field(None, alias="ID")


class PushSlotsMetaSource(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    Name_: Union[str, None] = Field(None, alias="Name")


class PushSlotsMetaTransmission(RedoxAbstractModel):
    ID_: Union[float, None] = Field(None, alias="ID")


class PushSlotsSlot(RedoxAbstractModel):
    DateTime_: str = Field(..., alias="DateTime")
    Duration_: float = Field(..., alias="Duration")
    ID_: Union[str, None] = Field(None, alias="ID")
    Location_: PushSlotsSlotLocation = Field(None, alias="Location")
    Provider_: PushSlotsSlotProvider = Field(None, alias="Provider")
    Reason_: Union[str, None] = Field(None, alias="Reason")


class PushSlotsSlotLocation(RedoxAbstractModel):
    Department_: Union[str, None] = Field(None, alias="Department")
    DepartmentIdentifiers_: List[PushSlotsSlotLocationDepartmentIdentifier] = Field(
        None, alias="DepartmentIdentifiers"
    )
    Facility_: Union[str, None] = Field(None, alias="Facility")
    FacilityIdentifiers_: List[PushSlotsSlotLocationFacilityIdentifier] = Field(
        None, alias="FacilityIdentifiers"
    )
    Room_: Union[str, None] = Field(None, alias="Room")
    Type_: Union[str, None] = Field(None, alias="Type")


class PushSlotsSlotLocationDepartmentIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class PushSlotsSlotLocationFacilityIdentifier(RedoxAbstractModel):
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")


class PushSlotsSlotProvider(RedoxAbstractModel):
    Address_: PushSlotsSlotProviderAddress = Field(None, alias="Address")
    Credentials_: List[str] = Field(None, alias="Credentials")
    EmailAddresses_: List[str] = Field(None, alias="EmailAddresses")
    FirstName_: Union[str, None] = Field(None, alias="FirstName")
    ID_: Union[str, None] = Field(None, alias="ID")
    IDType_: Union[str, None] = Field(None, alias="IDType")
    LastName_: Union[str, None] = Field(None, alias="LastName")
    PhoneNumber_: PushSlotsSlotProviderPhoneNumber = Field(None, alias="PhoneNumber")


class PushSlotsSlotProviderAddress(RedoxAbstractModel):
    City_: Union[str, None] = Field(None, alias="City")
    Country_: Union[str, None] = Field(None, alias="Country")
    County_: Union[str, None] = Field(None, alias="County")
    State_: Union[str, None] = Field(None, alias="State")
    StreetAddress_: Union[str, None] = Field(None, alias="StreetAddress")
    ZIP_: Union[str, None] = Field(None, alias="ZIP")


class PushSlotsSlotProviderPhoneNumber(RedoxAbstractModel):
    Office_: Union[str, None] = Field(None, alias="Office")


PushSlots.model_rebuild()
PushSlotsMeta.model_rebuild()
PushSlotsSlot.model_rebuild()
PushSlotsSlotLocation.model_rebuild()
PushSlotsSlotProvider.model_rebuild()
